---

# Our project/namespace...
namespace: fragalysis-cicd
namespace_display_name: "Fragalysis (Development)"
namespace_description: "The Fragalysis CI/CD Project (Development Deployment)"

# Project-specific variables
backup_nfs_dir: pv-fs-mysql-data-backup
backup_vol_name: fs-db-backup
deploy_backup: yes
deploy_jun2018_graph: no
deploy_molport_graph: no
graph_data_vol_name: fs-graph-data
graph_loader_vol_name: fs-graph-data-loader
graph_logs_vol_name: fs-graph-logs
input_vol_name: fs-input
jenkins_vol_name: fs-jenkins
mysql_vol_name: fs-mysql-data
use_nfs: yes
wait_for_mysql: yes
web_vol_name: fs-web-media

# Recovery PVs and PVCs - used when deploy_backup is 'yes'.
#
# There is an entry here for each namespace that we want to recover to.
# The first one is our own namespace, others are for the namespaces
# of others, like staging and production. Each shares a 'volume'
# but has its own 'name', 'claim' and 'namespace'
recovery_volumes:
  # Recovering from here (development) to dev
  dev:
    dir: pv-fs-mysql-data-backup
    volume_name: fs-db-recovery-dev
    volume_claim: fs-db-recovery-dev-claim
    namespace: fragalysis-cicd
  # Recovering from here to staging
  stag:
    dir: pv-fs-mysql-data-backup
    volume_name: fs-db-recovery-stag
    volume_claim: fs-db-recovery-dev-claim
    namespace: fragalysis-stag
  # Recovering from here to production
  prod:
    dir: pv-fs-mysql-data-backup
    volume_name: fs-db-recovery-prod
    volume_claim: fs-db-recovery-dev-claim
    namespace: fragalysis-prod

# If set ansible will attempt to configure Jenkins
# by running our configure-cicd.py module.
# This will require the environment variables to have been set.
configure_jenkins: no
