---

# Builds (and installs) slurm-DRMAA from source.

- name: Install build environment
  yum:
    name:
    - epel-release
    - gcc
    - mariadb-devel
    - mariadb-server
    - munge-devel
    - munge-libs
    - openssl
    - pam-devel
    - perl-ExtUtils-MakeMaker
    - python-pip
    - python-virtualenv
    - readline-devel
    - rpm-build

- name: Set DRMAA origin facts
  set_fact:
    drmaa_tarball: slurm-drmaa-{{ drmaa_version }}.tar.gz
    drmaa_unpacked: slurm-drmaa-{{ drmaa_version }}
    download_origin: github.com/natefoo/slurm-drmaa/releases/download

- name: Get DRMAA
  get_url:
    url: https://{{ download_origin }}/{{ drmaa_version }}/{{ drmaa_tarball }}
    dest: "{{ slurm_home_path }}/{{ drmaa_tarball }}"

- name: Unpack DRMAA
  unarchive:
    src: "{{ slurm_home_path }}/{{ drmaa_tarball }}"
    dest: "{{ slurm_home_path }}"
    creates: "{{ slurm_home_path }}/{{ drmaa_unpacked }}"
    remote_src: yes

- name: Configure DRMAA
  shell: ./configure
  args:
    chdir: "{{ slurm_home_path }}/{{ drmaa_unpacked }}"
    creates: "{{ slurm_home_path }}/{{ drmaa_unpacked }}/Makefile"

- name: Make DRMAA
  shell: make
  args:
    chdir: "{{ slurm_home_path }}/{{ drmaa_unpacked }}"

- name: Make Install DRMAA
  shell: make install
  args:
    chdir: "{{ slurm_home_path }}/{{ drmaa_unpacked }}"
