---

# Copy .zip files form the smiles directory to the target,
# unless the expected file is already present.
# Remember to zip the file using -j to avoid storing the full path.
- name: Copy and unzip SMILES to EFS
  unarchive:
    src: "{{ item }}"
    dest: "{{ efs_mount }}"
    creates: "{{ efs_mount }}/{{ item | regex_replace('^.*/(.+)[.]zip.*$', '\\1') }}"
  with_fileglob: ../smiles/*.zip
