---

# Deploy the project secrets

- name: Move to Fragalysis Project (Secrets)
  shell: oc project fragalysis-cicd
  changed_when: False

- name: Check Secrets
  shell: oc get secrets
  register: fs_secrets
  changed_when: False

- name: Create ISPyB Secrets
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-secrets-ispyb.yaml
    -p ISPYB_USER={{ ispyb_user }}
    -p ISPYB_PASSWORD="{{ ispyb_password }}"
    | oc create -f -
  when: '"fs-ispyb-secrets" not in fs_secrets.stdout'

- name: Create MySQL Secrets
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-secrets-mysql.yaml
    | oc create -f -
  when: '"fs-mysql-secrets" not in fs_secrets.stdout'

- name: Create Web Secrets
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-secrets-web.yaml
    | oc create -f -
  when: '"fs-web-secrets" not in fs_secrets.stdout'
