---

# Create the Nextflow cluster.
# This can be deleted with `nextflow cloud shutdown`
- name: Create cluster
  shell: "~/nextflow cloud create {{ nf_cloud_name }} -c {{ nf_cloud_size }} -y"
  args:
    chdir: "{{ efs_mount }}"
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
