---

# Used in conjunction with a backup this `Job` template
# restores a backup against a chosen database.
#
# oc process -f fs-restore.yaml | oc create -f -
# oc delete job --selector template=fs-restore

kind: Template
apiVersion: v1
metadata:
  name: fs-restore
  annotations:
    description: MySQL Revovery Template
    tags: mysql,backup,restore
labels:
  template: fs-restore
  app: fs-restore

parameters:

- name: RECOVERY_FROM_BACKUP
  value: latest
- name: RECOVERY_CLAIM_NAME
  value:

- name: RECOVERY_IMAGE
  value: informaticsmatters/sql-recovery:stable

objects:

- kind: Job
  apiVersion: batch/v1
  metadata:
    name: fs-restore
  spec:
    replicas: 1
    selector:
      name: fs-restore
    template:
      metadata:
        labels:
          name: fs-restore
      spec:
        nodeSelector:
          purpose: 'app'
        serviceAccountName: diamond

        containers:
        - image: ${RECOVERY_IMAGE}
          name: fs-restore
          volumeMounts:
          - name: backup-data
            mountPath: /backup

          env:
          - name: FROM_BACKUP
            value: ${RECOVERY_FROM_BACKUP}
          - name: MSHOST
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database-host
          - name: MSPORT
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database-port
          - name: MSUSER
            value: root
          - name: MSPASS
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database-root-password

        volumes:
        - name: backup-data
          persistentVolumeClaim:
            claimName: ${RECOVERY_CLAIM_NAME}
        restartPolicy: Never
