---

- name: Restart NetworkManager
  systemd:
    name: NetworkManager
    enabled: yes
    state: restarted
  become: yes

- name: Restart docker
  systemd:
    name: docker
    enabled: yes
    state: restarted
  become: yes
