---

- name: Set path facts
  set_fact:
    workflow_path: "{{ lookup('env','HOME') }}/{{ s_workflow_dir }}"
    standard_path: "{{ lookup('env','HOME') }}/{{ standard_dir }}"

# Clean-up before the run...
# The following task does not run if 'clean_start' is false.

- name: Remove existing directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - "{{ workflow_path }}"
  - "{{ standard_path }}"
  become: yes
  when: clean_start|bool

# Now ensure that the working directories exist
# and write some provenance information to the graph directory
# (which will eventually be uploaded to S3)

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ workflow_path }}"
  - "{{ standard_path }}"

# We're going to compile a new standard file from the defined
# 'raw' files. Go to S£ and get the next available standard number
# that we'll use as a path to store the results.

- name: Get a standard number
  shell: ./graph_get_unused_standard_number.py {{ path }}
  args:
    chdir: "{{ scripts }}"
  environment:
    FRAGALYSIS_S3_BUCKET: "{{ s3_bucket }}"
  vars:
    path: "{{ process_id }}"
  register: std_no_result
  changed_when: false

- name: Show standard number
  debug:
    msg: "{{ std_no_result.stdout }}"

- name: Set dynamic facts (Standard)
  set_fact:
    standard_number: "{{ std_no_result.stdout|int }}"

- name: Collect environment
  shell: env
  register: env_result

# Create 'provenance' files...

- name: Write DLS commit provenance
  copy:
    content: "{{ dls_commit_ref }}"
    dest: "{{ standard_path }}/dls-commit.prov"

- name: Write Fragalysis commit provenance
  copy:
    content: "{{ fragalysis_commit_ref }}"
    dest: "{{ standard_path }}/fragalysis_commit.prov"

- name: Write raw provenance
  copy:
    content: "{{ process_id }}"
    dest: "{{ standard_path }}/raw.prov"

- name: Write enviornment provenance
  copy:
    content: "{{ env_result.stdout }}"
    dest: "{{ standard_path }}/env.prov"

- name: Copy playbook parameter file
  copy:
    src: "{{ role_path }}/../../parameters"
    dest: "{{ standard_path }}/parameters.prov"
