---

- name: Create EFS mount point
  file:
    path: "{{ efs_mount }}"
    state: directory
  become: yes

# The nextflow mount command: -
#
#        zone="\$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)"
#        region="\${zone::-1}"
#        command -v nfsstat >/dev/null 2>&1 || yum install -y nfs-utils || apt-get -y install nfs-common
#        mkdir -p $fileSystemMount
#        mount -t nfs4 -o nfsvers=4.1 \${zone}.${fileSystemId}.efs.\${region}.amazonaws.com:/ $fileSystemMount
#        chown ${userName}:${userName} $fileSystemMount
#        chmod 775 $fileSystemMount
#
# From: -
#
#     https://github.com/nextflow-io/nextflow/blob/81e8d49f014a990cce1d1be4afb84e1fdd93840c/src/main/groovy/
#         nextflow/cloud/aws/AmazonCloudDriver.groovy#L329-L335
- name: Mount EFS
#  shell: "mount -t efs {{ efs_id }}:/ {{ efs_mount }}"
  mount:
    path: "{{ efs_mount }}"
    src: "{{ efs_id }}:/"
    fstype: efs
    state: present
  become: yes

- name: Change EFS ownership
  file:
    path: "{{ efs_mount }}"
    mode: "go+rw"
  become: yes
