---

# Our project/namespace...
graph_2_namespace: fragalysis-graph-2
graph_2_namespace_display_name: Fragalysis (Graph 2)
graph_2_namespace_description: >
  The Fragalysis Graph '2' Project.
  Hosting a neo4j graph database.

graph_2_use_nfs: yes
graph_2_pagecache: 350g
