---

# Deploy the project secrets

- name: Check Secrets
  shell: oc get secrets
  register: fs_secrets
  changed_when: False

- name: Create MySQL Secrets
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-secrets-mysql.yaml
    -p MYSQL_NAME={{ mysql_name }}
    | oc create -f -
  when: not fs_secrets.stdout | regex_search('^fs-mysql-secrets\s', multiline=True)
