---

# Install packages for MUNGE, slurm and other stuff

- name: Install addtional packages
  yum:
    name:
    - epel-release
    - nfs-utils
    - nfs-utils-lib

# Setup NFS share and head node mounts

- name: Create home
  file:
    path: /home
    state: directory
    mode: 0777
    owner: root
    group: root

- name: Ensure device has a filesystem
  filesystem:
    fstype: ext4
    force: yes
    dev: "{{ os_slurm_volume_device }}"

- name: Mount home
  mount:
    name: /home
    src: "{{ os_slurm_volume_device }}"
    fstype: auto
    opts: defaults,nobootwait
    passno: 2
    state: mounted

- name: Copy exports
  copy:
    content: /home *(rw,no_root_squash)
    dest: /etc/exports
    owner: root
    group: root
  notify: Restart NFS
