---

- import_tasks: fs-p-project.yaml
- import_tasks: fs-p-cicd.yaml
- import_tasks: fs-p-secrets.yaml
- import_tasks: fs-p-mysql.yaml
- import_tasks: fs-p-web.yaml

- import_tasks: fs-p-backup.yaml
  when: backup_deploy|bool
