---

# Our project/namespace...
namespace: fragalysis-dev
namespace_display_name: "Fragalysis (Development)"
namespace_description: "The Fragalysis Project (Development Namespace)"

# Backup/Recovery
backup_nfs_dir: pv-fs-mysql-data-backup
backup_vol_name: fs-db-backup
backup_deploy: no

input_vol_name: fs-d-input

wait_for_mysql: yes
