---

# Setup the Graph-2 Project.
# Ths includes the project and its service account.

- name: Login (admin at {{ cluster_url }})
  shell: oc login {{ cluster_url }} -u admin -p {{ admin_password }}
  changed_when: False

- name: Get Projects
  shell: oc get projects
  register: projects_result
  changed_when: False

- name: Create Graph Project
  shell: >
    oc new-project {{ graph_2_namespace }}
    --display-name="{{ graph_2_namespace_display_name }}"
    --description="{{ graph_2_namespace_description }}"
  when: graph_2_namespace not in projects_result.stdout

- name: Move to Graph Project
  shell: oc project {{ graph_2_namespace }}
  changed_when: False

- name: Check Diamond Service Account exists
  shell: oc get sa
  register: sa_result
  changed_when: False

- name: Create Diamond Service Account (Graph Project)
  shell: "{{ item }}"
  loop:
  - oc create sa {{ service_account }}
  - oc adm policy add-role-to-user admin -z {{ service_account }}
  - oc adm policy add-scc-to-user anyuid -z {{ service_account }}
  when: service_account not in sa_result.stdout
