---

# Removes the Graph 2 deployment.
# This essentially consists of removing the project (and waiting for it)
# and then removing the persistent volumes we expect to exist.

- name: Delete Fragalysis GRAPH 2 Project?
  pause:
    prompt: |-
      Delete the GRAPH-2 project from {{ cluster_url }}?
      Hit return to delete it.
      Hit Ctrl+c and then "a" if you've changed your mind.

# Go...

- name: Login (admin at {{ cluster_url }})
  shell: oc login {{ cluster_url }} -u admin -p {{ admin_password }}
  changed_when: False

# Remove Graph-2 namespace

- name: Check projects
  shell: oc get projects
  register: p_result
  changed_when: False

- name: Delete Graph-2 project
  shell: oc delete project/{{ graph_2_namespace }}
  when: graph_2_namespace in p_result.stdout

- name: Wait for Graph-2 project deletion
  shell: oc get projects
  register: wait_cmd
  retries: 12
  delay: 10
  until: graph_2_namespace not in wait_cmd.stdout
  changed_when: False

# Remove Persistent Volumes

- name: Check Graph-2 Persistent Volumes
  shell: oc get pv
  register: pv_result
  changed_when: False

- name: Delete Graph-2 Persistent Volumes
  shell: oc delete pv/{{ item }}
  loop:
  - 'fs-graph-molport-data-loader'
  when: item in pv_result.stdout
