---

# Bastion-specific configuration

- name: Install PIP
  easy_install:
    name: pip
    state: latest
  become: yes

- name: Install Python packages
  pip:
    name:
    - ansible==2.7.9
    - future==0.17.1
    - jinja2==2.10
    - passlib==1.7.1
    - pyyaml==3.10
  become: yes

# Additional Bastion system configuration
# here we install and configure 'dnsmasq'

- name: Install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - bind-utils
      - dnsmasq
  become: yes

- name: Adjust reolv.conf (search)
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^search openstacklocal'
    line: 'search openstacklocal novalocal'
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Adjust reolv.conf (insert localhost nameserver)
  lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 127.0.0.1'
    insertafter: '^search '
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Protect resolv.conf from the NetworkManager
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    line: 'dns=done'
    insertafter: '^[main]'
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Adjust dnsmasq.conf (no-resolv)
  lineinfile:
    path: /etc/dnsmasq.conf
    regexp: '^#no-resolv$'
    line: 'no-resolv'
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Adjust dnsmasq.conf (add servers)
  lineinfile:
    path: /etc/dnsmasq.conf
    insertafter: '^#server'
    firstmatch: yes
    line: server={{ item }}
    owner: root
    group: root
    mode: 0644
  with_items: '{{ nameservers }}'
  become: yes

- name: Restart dnsmasq
  systemd:
    name: dnsmasq.service
    enabled: yes
    state: restarted
  become: yes
