---

- hosts: localhost
  gather_facts: No

  vars:
    namespace: fragalysis-tibor
    deploy_backup: no
    input_vol_name: fs-tibor-input

  tasks:
  - name: Run the Fragalysis Undeploy Tasks
    include_role:
      name: fragalysis-stack-prod
      tasks_from: fs-p-undeploy.yaml
