---

- name: Install worker packages
  yum:
    name:
    - epel-release
    - nfs-utils
    - nfs-utils-lib

# We need to be able to resolve between our name and IP
# on the head node. Workers also need to be able to
# locate the head node by name so their hosts files
# are also adjusted.

- name: Adjust /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "{{ line }}"
    line: "{{ line }}"
  vars:
    line: "{{ head_addr }} {{ slurm_instance_base_name }}-head"

# Mount NFS share

- name: Enable and restart NFS
  service:
    name: nfs
    enabled: yes
    state: restarted

- name: Create slurm (home) mount-point
  file:
    path: "{{ slurm_home_path }}"
    state: directory
    mode: 0777
    owner: root
    group: root

- name: Mount slurm (home)
  mount:
    path: "{{ slurm_home_path }}"
    src: "{{ nfs_ip }}:{{ slurm_home_path }}"
    fstype: nfs
    opts: defaults
    passno: '2'
    state: mounted
  vars:
    nfs_ip: "{{ head_addr }}"
