---

# Copy Nextflow files
- name: Copy Nextflow job files
  copy:
    src: "{{ item }}"
    dest: "{{ efs_mount }}/"
  loop:
  - ../nextflow/graph.nf

# Copy the defined .zip file from the smiles directory to the target,
# unless the expected file is already present.
# Remember to zip the file using -j to avoid storing the full path.
- name: Copy and unzip SMILES to EFS
  unarchive:
    src: "../smiles/{{ graph_origin }}.zip"
    dest: "{{ efs_mount }}"
