---

# Builds slurm from source.
# This is typically only done on the head node.
# The workers (and the head installation)
# will use the produced RPM, which is
# deposited on the shared file-system.

- name: Install build environment
  yum:
    name:
    - epel-release
    - gcc
    - mariadb-devel
    - mariadb-server
    - munge-devel
    - munge-libs
    - openssl
    - pam-devel
    - perl-ExtUtils-MakeMaker
    - python-pip
    - python-virtualenv
    - readline-devel
    - rpm-build

- name: Get slurm
  get_url:
    url: https://download.schedmd.com/slurm/slurm-{{ slurm_version }}.tar.bz2
    dest: "{{ slurm_home_path }}/slurm-{{ slurm_version }}.tar.bz2"

- name: Build slurm
  shell: rpmbuild -ta slurm-{{ slurm_version }}.tar.bz2
  args:
    chdir: "{{ slurm_home_path }}"

- name: Move slurm
  shell: mv /root/rpmbuild {{ slurm_home_path}}/rpmbuild
  creates: {{ slurm_home_path}}/rpmbuild
