---

# Install packages slurm

- name: Install slurm packages
  yum:
    name:
    - epel-release
    - openssl
    - numactl
    - hwloc
    - lua
    - libibmad
    - libibumad

- name: Crete slurm group
  group:
    gid: "{{ slurm_user_id }}"
    name: slurm
#  notify: Restart slurm

- name: Crete slurm user
  user:
    name: slurm
    uid: "{{ slurm_user_id }}"
    group: slurm
    home: "{{ slurm_home_path }}"
    create_home: no
    shell: /sbin/bash
#  notify: Restart slurm

- name: Create slurm config directory
  file:
    path: /etc/slurm
    state: directory
    owner: slurm
    recurse: true
#  notify: Restart slurm

- name: Display worker nodes
  debug:
    msg: "{{ hostvars['localhost']['worker_nodes'] }}"

- name: Copy slurm configuration template
  template:
    src: "{{ role_path }}/files/slurm.conf.j2"
    dest: /etc/slurm/slurm.conf
    owner: slurm
  vars:
    worker_nodes: "{{ hostvars['localhost']['worker_nodes'] }}"
#  notify: Restart slurm

- name: Copy slurm cgroup configuration
  copy:
    src: "{{ role_path }}/files/cgroup.conf"
    dest: /etc/slurm/cgroup.conf
    owner: slurm
#  notify: Restart slurm

- name: Copy slurm cgroup allowed devices configuration
  copy:
    src: "{{ role_path }}/files/cgroup_allowed_devices_file.conf"
    dest: /etc/slurm/cgroup_allowed_devices_file.conf
    owner: slurm
#  notify: Restart slurm

- name: Configure slurmd directory
  file:
    path: /var/spool/slurmd
    state: directory
    mode: 0755
    owner: slurm
    group: slurm
    recurse: true
#  notify: Restart slurm

- name: Touch slurm log
  file:
    path: /var/log/slurmd.log
    owner: slurm
    group: slurm
    state: touch
#  notify: Restart slurm
