---

# Our project/namespace...
namespace: fragalysis-prod
namespace_display_name: "Fragalysis (Production)"
namespace_description: "The Fragalysis Project (Production Deployment)"

# The namespace of the Test/CICD Fragalysis deployment.
# This is used to allow us to get a reference to services exposed there
# (i.e. the Graph database). it should match the value of
# the namespace you used when deploying the fragalysis-cicd role.
fragalysis_cicd_namespace: fragalysis-cicd

backup_nfs_dir: pv-fs-p-mysql-data-backup
backup_vol_name: fs-p-db-backup
backup_h_schedule: "20 * * * *"
backup_deploy: no
backup_enable_rsync: yes
backup_rsync_path: /dls/verne/fs-production

input_vol_name: fs-p-input

mysql_name: mysql-prod
wait_for_mysql: yes

web_hostname: fragalysis.xchem.informaticsmatters.com
web_name: web-prod
web_image_tag: stable
