---

# The Fragalysis Stack's Neo4J Graph database Image Stream deployment.
#
# oc process -f fs-graph-is.yaml | oc create -f -
# oc delete all --selector template=fs-graph-is

kind: Template
apiVersion: v1
metadata:
  name: fs-graph-is
  annotations:
    description: Fragalysis Stack's Neo4J ImageStream Definition
    tags: fragalysis,graph,neo4j
labels:
  template: fs-graph-is

parameters:

- name: GRAPH_TAG
  value: 'latest'

objects:

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: graph-stream
  spec:
    tags:
    - from:
        kind: DockerImage
        name: xchem/graph:${GRAPH_TAG}
      name: latest
