#!groovy​

// The Fragalysis Graph Database Builder.

pipeline {

  agent { label 'buildah-slave' }

  environment {
    GRAPH_IMAGE = 'xchem/graph:latest'
  }

  stages {

    stage('Inspect') {
      steps {
        dir('images/graph') {
          script {
            DATA_ORIGIN = sh(script: './get_unbuilt_data_directory.py', returnStdout: true).trim()
          }
        }
      }
    }

    stage('Build') {
      when {
        expression { DATA_ORIGIN.length() > 0 }
      }
      steps {
        dir('images/graph') {
          echo "Building ${DATA_ORIGIN}..."
          sh "cp /source-data/${DATA_ORIGIN}/* data-loader"
          sh "buildah bud --format docker --build-arg DATA_ORIGIN=$DATA_ORIGIN -f Dockerfile -t ${env.GRAPH_IMAGE}"
        }
      }
    }

  }

}
