#!groovy​

// The Fragalysis Graph Database Builder.

pipeline {

  agent { label 'buildah-slave' }

  stages {

    stage('Check') {
      steps {
        dir('images/graph') {
          script {
            DATA_DIR = sh(script: './get_unbuilt_data_directory.py', returnStdout: true).trim()
          }
        }
      }
    }

    stage('Build') {
      when {
        expression { DATA_DIR.length() == 0 }
      }
      steps {
        dir('images/graph') {
          echo "Building ${DATA_DIR}..."
        }
      }
    }

  }

}
