---

# The Fragalysis Stack's database backup deployment (hourly).
#
# oc process -f fs-db-backup-h.yaml | oc create -f -
# oc delete all --selector template=fs-db-backup-h

kind: Template
apiVersion: v1
metadata:
  name: fs-db-backup-h
  annotations:
    description: Fragalysis Stack's Postgres Backup
    tags: fragalysis,db,postgres
labels:
  template: fs-db-backup-h

parameters:

- name: BACKUP_REGISTRY
  value: 'docker.io'
- name: BACKUP_IMAGE
  value: 'informaticsmatters/sql-backup'
- name: BACKUP_TAG
  value: 'stable'
- name: BACKUP_H_SCHEDULE
  value: '5 * * * *'
- name: BACKUP_H_COUNT
  value: '24'

objects:

# The HOURLY CronJob (at HH:05)
# This job will create new postgres backups every hour
# Keeping the last 24 backups in the directory /backup/hourly
- kind: CronJob
  apiVersion: batch/v1beta1
  metadata:
    name: db-backup-hourly
  spec:
    schedule: ${BACKUP_H_SCHEDULE}
    startingDeadlineSeconds: 180
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              name: backup-hourly
          spec:
            nodeSelector:
              purpose: 'app'
            serviceAccountName: diamond

            # Application containers
            containers:
            - image: ${BACKUP_REGISTRY}/${BACKUP_IMAGE}:${BACKUP_TAG}
              name: backup
              imagePullPolicy: Always
              volumeMounts:
              - name: fs-data-backup
                mountPath: /backup
              env:
              - name: BACKUP_TYPE
                value: hourly
              - name: BACKUP_COUNT
                value: ${BACKUP_H_COUNT}
              - name: MSHOST
                valueFrom:
                  secretKeyRef:
                    name: fs-mysql-secrets
                    key: database-host
              - name: MSPORT
                valueFrom:
                  secretKeyRef:
                    name: fs-mysql-secrets
                    key: database-port
              - name: MSUSER
                value: root
              - name: MSPASS
                valueFrom:
                  secretKeyRef:
                    name: fs-mysql-secrets
                    key: database-root-password
            volumes:
            - name: fs-data-backup
              persistentVolumeClaim:
                claimName: fs-db-backup-claim
            restartPolicy: Never
