---

# The Application's Persistent Volume Claims.
#
# oc process -f fs-db-recovery-pvc.yaml | oc create -f -
# oc delete pvc --selector template=fs-db-recovery-pvc

kind: Template
apiVersion: v1
metadata:
  name: fs-db-recovery-pvc
  annotations:
    description: Fragalysis Stack's Persistent Volume Claims
    tags: fragalysis,db,postgres
labels:
  template: fs-db-recovery-pvc

parameters:

- name: RECOVERY_VOLUME_CLAIM_NAME
  value: fs-db-recovery-claim
- name: RECOVERY_VOLUME_NAME
  value: fs-db-recovery
- name: RECOVERY_PV_BACKUP_SIZE
  value: 100Gi

objects:

# ----------------------
# Recovery Volume Claims
# ----------------------

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${RECOVERY_VOLUME_CLAIM_NAME}
  spec:
    accessModes:
    - ReadOnlyMany
    volumeName: ${RECOVERY_VOLUME_NAME}
    resources:
      requests:
        storage: ${RECOVERY_PV_BACKUP_SIZE}
