---

# The Fragalysis Stack's Neo4J Graph database deployment.
#
# oc process -f fs-graph-svc.yaml | oc create -f -
# oc delete svc --selector template=fs-graph-svc

kind: Template
apiVersion: v1
metadata:
  name: fs-graph-svc
  annotations:
    description: Fragalysis Stack's Neo4J Service Definition
    tags: fragalysis,graph,neo4j
labels:
  template: fs-graph-svc

parameters:

objects:

- kind: Service
  apiVersion: v1
  metadata:
    name: neo4j
  spec:
    ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687
    selector:
      name: graph
