---

# The Graph Database Persistent Volume Claims.
#
# oc process -f fs-graph-jun2018-pvc.yaml | oc create -f -
# oc delete pvc --selector template=fs-graph-jun2018-pvc

kind: Template
apiVersion: v1
metadata:
  name: fs-graph-jun2018-pvc
  annotations:
    description: Fragalysis Stack's Persistent Volume Claims
    tags: fragalysis,db,postgres
labels:
  template: fs-graph-jun2018-pvc

parameters:

- name: GRAPH_DATA_LOADER_SIZE
  value: 300Gi
- name: GRAPH_DATA_SIZE
  value: 500Gi
- name: GRAPH_LOGS_SIZE
  value: 2Gi

objects:

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: fs-graph-jun2018-data-claim
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${GRAPH_DATA_SIZE}

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: fs-graph-jun2018-data-loader-claim
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${GRAPH_DATA_LOADER_SIZE}

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: fs-graph-jun2018-logs-claim
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${GRAPH_LOGS_SIZE}
