---

# The Input Data's Persistent Volume Claims.
#
# oc process -f fs-input-pvc.yaml | oc create -f -
# oc delete pvc --selector template=fs-input-pvc

kind: Template
apiVersion: v1
metadata:
  name: fs-input-pvc
  annotations:
    description: Fragalysis Stack's Input Data Persistent Volume Claims
    tags: fragalysis,input
labels:
  template: fs-input-pvc

parameters:

- name: INPUT_PV_SIZE
  value: 500Gi
- name: INPUT_VOLUME_NAME
  value: fs-input
- name: INPUT_CLAIM_NAME
  value: fs-input-claim

objects:

  # To avoid the claim from expecting a volume
  # in the default storage class (glusterfs-storage)
  # we set the storage-class annotation to a blank string (' ').
  # This must be bound to a named PV
  # and must not use the default storage class
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${INPUT_CLAIM_NAME}
    annotations:
      volume.beta.kubernetes.io/storage-class: ' '
  spec:
    accessModes:
    - ReadOnlyMany
    volumeName: ${INPUT_VOLUME_NAME}
    resources:
      requests:
        storage: ${INPUT_PV_SIZE}
