---

# The Application's Persistent Volumes (NFS).
#
# oc process -f fs-web-pv-nfs.yaml | oc create -f -
# oc delete pv --selector template=fs-web-pv-nfs

kind: Template
apiVersion: v1
metadata:
  name: fs-web-pv-nfs
  annotations:
    description: Fragalysis Stack's Persistent Volumes (using NFS)
    tags: fragalysis,web
labels:
  template: fs-web-pv-nfs

parameters:

- name: NFS_SERVER
  value: bastion.novalocal
- name: NFS_PATH
  value: /data

- name: WEB_NAMESPACE
  value: fragalysis-cicd
- name: WEB_VOLUME_NAME
  value: fs-web-media
- name: WEB_VOLUME_CLAIM_NAME
  value: fs-web-media-claim
- name: WEB_MEDIA_PV_DIR
  value: pv-fs-web-media
- name: WEB_MEDIA_PV_SIZE
  value: 20Gi

objects:

# --------------------------
# Web (Django Media) Volumes
# --------------------------

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: ${WEB_VOLUME_NAME}
  spec:
    capacity:
      storage: ${WEB_MEDIA_PV_SIZE}
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/${WEB_MEDIA_PV_DIR}
    claimRef:
      name: ${WEB_VOLUME_CLAIM_NAME}
      namespace: ${WEB_NAMESPACE}
