---

# The Fragalysis Stack's Web (Front-End) deployment.
#
# oc process -f fs-web-svc.yaml | oc create -f -
# oc delete svc --selector template=fs-web-svc

kind: Template
apiVersion: v1
metadata:
  name: fs-web-svc
  annotations:
    description: Fragalysis Stack's Web Service Definition
    tags: fragalysis,web,svc
labels:
  template: fs-web-svc

parameters:

- name: WEB_NAME
  value: web

objects:

- kind: Service
  apiVersion: v1
  metadata:
    name: ${WEB_NAME}
  spec:
    ports:
    - name: http
      port: 8000
      targetPort: 80
    selector:
      name: ${WEB_NAME}
