---

- name: Move to Fragalysis (TEST) Project (Backup)
  shell: oc project fragalysis-cicd

# Create the MySQL PV

- name: Check Backup PV
  shell: oc get pv
  register: bu_pv
  when:
  - deploy_backup
  - use_nfs

- name: Create Backup PV
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-db-backup-pv-nfs.yaml |
    oc create -f -
  when:
  - deploy_backup
  - use_nfs
  - '"fs-db-backup" not in bu_pv.stdout'

# Create the Backup PVCs

- name: Check Backup PVC
  shell: oc get pvc
  register: bu_pvc
  when:
  - deploy_backup

- name: Create Backup PVC
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-db-backup-pvc.yaml |
    oc create -f -
  when:
  - deploy_backup
  - '"fs-db-backup-claim" not in bu_pvc.stdout'

# Create the Backup Deployment

- name: Check Backup Deployment
  shell: oc get cronjobs
  register: bu_cj
  when: deploy_backup

- name: Create Graph Deployment
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-db-backup.yaml |
    oc create -f -
  when:
  - deploy_backup
  - '"db-backup-hourly" not in bu_cj.stdout'

# We don't wait for this job,
# its deployment is controlled by Cron.
