---

- name: Move to Fragalysis (TEST) Project
  shell: oc project fragalysis-cicd

# Create the Graph Deployment

- name: Check Graph Deployment
  shell: oc get deploymentconfigs
  register: graph_dc

- name: Create Graph Deployment
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-graph.yaml |
    oc create -f -
  when: '"graph" not in graph_dc.stdout'

# We don't wait for this pod,
# its deployment is controlled by Jenkins.
