---

- name: Move to Fragalysis (TEST) Project
  shell: oc project fragalysis-cicd

# Create the MySQL PV

- name: Check MySQL PV
  shell: oc get pv
  register: mysql_pv

- name: Create MySQL PV
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-mysql-pv-nfs.yaml |
    oc create -f -
  when: '"fs-mysql-data" not in mysql_pv.stdout'

# Create the MySQL PVCs

- name: Check MySQL PVC
  shell: oc get pvc
  register: mysql_pvc

- name: Create MySQL PVC
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-mysql-pvc.yaml |
    oc create -f -
  when: '"fs-mysql-data-claim" not in mysql_pvc.stdout'

# Create the MySQL Deployment

- name: Check MySQL Deployment
  shell: oc get deploymentconfigs
  register: mysql_dc

- name: Create MySql Deployment
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-mysql.yaml |
    oc create -f -
  when: '"mysql" not in mysql_dc.stdout'

# Wait...

- name: Wait for MySQL
  shell: oc get po | grep mysql | grep -v deploy | grep 1/1 > /dev/null
  retries: 15
  delay: 20
  register: result
  until: result.rc == 0
  when: wait_for_mysql
