---

# Deploy the project secrets

- name: Move to Fragalysis (TEST) Project
  shell: oc project fragalysis-cicd

- name: Check Secrets
  shell: oc get secrets
  register: fs_secrets

- name: Create Secrets
  shell: >
    oc process -f {{ t_dir }}/fs-secrets.yaml
    -p ISPYB_USER={{ ispyb_user }}
    -p ISPYB_PASSWORD={{ ispyb_password }} | oc create -f -
  when: '"fs-secrets" not in fs-secrets.stdout'
