---

# Check the mount, which controls which oif the following tasks is run.
# We have to handle the command failure when the mount does not exist.
- name: Check EFS mount point
  shell: mountpoint efs-mount-point
  register: mount_stat
  failed_when: mount_stat.rc == 2

- name: Create EFS mount point
  file:
    path: efs-mount-point
    state: directory
  when: '"is a mountpoint" not in mount_stat.stdout'

- name: Mount EFS
  shell: "mount -t nfs -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport {{ efs_dns_name }}:/ efs-mount-point"
  become: yes
  when: '"is a mountpoint" not in mount_stat.stdout'

- name: Change EFS ownership
  file:
    path: efs-mount-point
    mode: "go+rw"
  become: yes
