---

# Our project/namespace...
namespace: fragalysis-prod
namespace_display_name: "Fragalysis (Production)"
namespace_description: "The Fragalysis Project (Production Deployment)"

# The namespace of the Test/CICD Fragalysis deployment.
# This is used to allow us to get a reference to services exposed there
# (i.e. the Graph database). it should match the value of
# the namespace you used when deploying the fragalysis-cicd role.
fragalysis_cicd_namespace: fragalysis-cicd

# Project-specific variables
backup_nfs_dir: pv-fs-p-mysql-data-backup
backup_vol_name: fs-p-db-backup
deploy_backup: yes
deploy_jun2018_graph: no
graph_svc: neo4j.{{ fragalysis_cicd_namespace }}.svc
graph_bolt_url: bolt://neo4j:test@neo4j.{{ fragalysis_cicd_namespace }}.svc:7687
input_vol_name: fs-p-input
mysql_name: mysql-prod
mysql_nfs_dir: pv-fs-p-mysql-data
mysql_vol_name: fs-p-mysql-data
use_nfs: yes
wait_for_mysql: yes
web_hostname: fragalysis.diamond.ac.uk
web_name: web-prod
web_nfs_dir: pv-fs-p-web-media
web_vol_name: fs-p-web-media
web_image_tag: stable

# Recovery PVs and PVCs - used when deploy_backup is 'yes'.
#
# There is an entry here for each namespace that we want to recover to.
# The first one is our own namespace, others are for the namespaces
# of others, like staging and dev. Each shares an (NFS) 'directory'
# but has its own 'name', 'claim' and 'namespace'
recovery_volumes:
  # Recovering from here (prod) to prod
  dev:
    dir: pv-fs-p-mysql-data-backup
    volume_name: fs-p-db-recovery-prod
    volume_claim: fs-db-recovery-prod-claim
    namespace: fragalysis-prod
  # Recovering from here to staging
  stag:
    dir: pv-fs-p-mysql-data-backup
    volume_name: fs-p-db-recovery-stag
    volume_claim: fs-db-recovery-prod-claim
    namespace: fragalysis-stag
  # Recovering from here to development
  prod:
    dir: pv-fs-p-mysql-data-backup
    volume_name: fs-p-db-recovery-dev
    volume_claim: fs-db-recovery-prod-claim
    namespace: fragalysis-cicd
