---

- name: Set path facts
  set_fact:
    combiner_path: "{{ lookup('env', 'HOME') }}/{{ combiner_dir }}"
    tmp_path: "{{ tmp_dir }}"

# Clean-up before the run...
# The following task does not run if 'clean_start' is false.

- name: Remove existing directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - "{{ combiner_path }}"
  - "{{ tmp_path }}"
  when: clean_start|bool

# Now ensure that the working directories exist
# and write some provenance information to the combination directory
# (which will eventually be uploaded to S3)

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ combiner_path }}"
  - "{{ tmp_path }}"

- name: Get a combination number
  shell: ./graph_get_unused_combination_number.py
  args:
    chdir: "{{ scripts }}"
  environment:
    FRAGALYSIS_S3_BUCKET: "{{ s3_bucket }}"
  register: combination_no_result
  changed_when: false

- name: Show combination number
  debug:
    msg: "{{ combination_no_result.stdout }}"

- name: Set dynamic facts (Combination)
  set_fact:
    combination_number: "{{ combination_no_result.stdout|int }}"

- name: Collect environment
  shell: env
  register: env_result

# Create 'provenance' files...

- name: Write DLS commit provenance
  copy:
    content: "{{ dls_commit_ref }}"
    dest: "{{ combiner_path }}/dls-commit.prov"

- name: Write Fragalysis commit provenance
  copy:
    content: "{{ fragalysis_commit_ref }}"
    dest: "{{ combiner_path }}/fragalysis_commit.prov"

- name: Write environment provenance
  copy:
    content: "{{ env_result.stdout }}"
    dest: "{{ combiner_path }}/env.prov"

- name: Copy playbook parameter file
  copy:
    src: "{{ role_path }}/../../parameters"
    dest: "{{ combiner_path }}/parameters.prov"
