---

# Creates a system-wisde (shared) bin directory.
# The location is also placed in a file in /etc/profile.d
# as a PATH declaration

- name: Create system-wide bin directory
  file:
    path: "{{ bin_dir }}"
    state: directory
    owner: root
    group: root
    mode: 755

- name: Set profile PATH
  template:
    src: cloud-path.sh.j2
    dest: /etc/profile.d/cloud-path.sh
    owner: root
    group: root
    mode: 644
