---

# We use the content of the "<cluster base name>.munge.key" file
# for the MUNGE key or, if it doesn't exist, generate a new one,
# writing it to the key file for the next iteration.

- name: Set MUNGE key filename
  set_fact:
    munge_key_filename: "{{ hostvars['localhost']['base_name'] }}.munge.key"

- name: Check local MUNGE file
  stat:
    path: "{{ munge_key_filename }}"
  register: key_file
  delegate_to: 127.0.0.1

- name: Create MUNGE key
  set_fact:
    munge_key: "{{ lookup('password', '/dev/null length=1024') }}"
  when: not key_file.stat.exists

- name: Write created MUNGE key
  copy:
    content: "{{ munge_key }}"
    dest: "{{ munge_key_filename }}"
  delegate_to: 127.0.0.1
  when: not key_file.stat.exists

- name: Retrieve MUNGE key
  set_fact:
    munge_key: "{{ lookup('file', munge_key_filename ) }}"
  delegate_to: 127.0.0.1
  when: key_file.stat.exists
