---

- name: Install head packages
  yum:
    name:
    - epel-release
    - nfs-utils
    - nfs-utils-lib

# Setup NFS share and head node mounts

# Ansible provides a 'ansible_mounts' variable.
# It's a map of mounts and we just want to know if
# our mount (slurm_home_path) is in it.
#
# The map looks something like this (ansible 2.7.10): -
#
# "ansible_mounts": [{
#            "block_available": 122405946,
#            "block_size": 4096,
#            "block_total": 128982080,
#            "block_used": 6576134,
#            "device": "/dev/vdb",
#            "fstype": "ext4",
#            "inode_available": 32767989,
#            "inode_total": 32768000,
#            "inode_used": 11,
#            "mount": "/slurm-home",
#            "options": "rw,relatime,data=ordered",
#            "size_available": 501374754816,
#            "size_total": 528310599680,
#            "uuid": "dc613974-7fc1-48ad-9448-b78003aecaa5"
#        }]

- name: Inspect slurm (home) mount
  set_fact:
    mounted: "{{ ansible_mounts|json_query(query)|length }}"
  vars:
    query: "[?mount=='{{ slurm_home_path }}']"

- name: Create slurm (home) mount-point
  file:
    path: "{{ slurm_home_path }}"
    state: directory
    mode: 0777
    owner: root
    group: root
  when: not mounted|bool

- name: Unmount device
  mount:
    path: "{{ slurm_home_path }}"
    state: unmounted
  when: not mounted|bool

- name: Ensure device has a filesystem
  filesystem:
    fstype: ext4
    dev: "{{ os_volume_device }}"
  when: not mounted|bool

- name: Mount device
  mount:
    src: "{{ os_volume_device }}"
    path: "{{ slurm_home_path }}"
    fstype: ext4
    opts: defaults
    passno: 2
    state: mounted
  when: not mounted|bool

- name: Create NFS exports
  copy:
    content: "{{ slurm_home_path }} *(rw,no_root_squash)"
    dest: /etc/exports
    owner: root
    group: root
  notify: Restart NFS

- import_tasks: create-munge-key.yaml
