---

- name: Inspect slurm (home) mount
  set_fact:
    mounted_test: "{{ ansible_mounts|json_query(query)|length }}"
  vars:
    query: "[?mount=='no-such-path']"

- name: debug
  debug:
    var: mounted_test

- name: Install head packages
  yum:
    name:
    - epel-release
    - nfs-utils
    - nfs-utils-lib

# Setup NFS share and head node mounts
# The

- name: Inspect slurm (home) mount
  set_fact:
    mounted: "{{ ansible_mounts|json_query(query)|length }}"
  vars:
    query: "[?mount=='{{ slurm_home_path }}']"

- name: Create slurm (home) mount-point
  file:
    path: "{{ slurm_home_path }}"
    state: directory
    mode: 0777
    owner: root
    group: root
  when: not mounted|bool

- name: Unmount device
  mount:
    path: "{{ slurm_home_path }}"
    state: unmounted
  when: not mounted|bool

- name: Ensure device has a filesystem
  filesystem:
    fstype: ext4
    dev: "{{ os_volume_device }}"
  when: not mounted|bool

- name: Mount device
  mount:
    src: "{{ os_volume_device }}"
    path: "{{ slurm_home_path }}"
    fstype: ext4
    opts: defaults
    passno: 2
    state: mounted
  when: not mounted|bool

- name: Create NFS exports
  copy:
    content: "{{ slurm_home_path }} *(rw,no_root_squash)"
    dest: /etc/exports
    owner: root
    group: root
  notify: Restart NFS

- import_tasks: create-munge-key.yaml
