# A dockerfile to build the Image Loader using the latest xchem backend code.
#
# Build, when the backend code has changed, with something like: -
#
#   docker build . -f Dockerfile-local -t loader:latest
#
# Then, to load the 2018-10-24T18 stack media data from the directory
# /input (that contains a 'django_media' directory) to the directory /output,
# run with: -
#
#   docker run --rm
#     -e DATA_ORIGIN=2018-10-24T18
#     -e MYSQL_HOST=<host>
#     -e MYSQL_PORT=<port>
#     -e MYSQL_USER=<user>
#     -e MYSQL_PASSWORD=<password>
#     -e MYSQL_DATABASE=<db>
#     -e MYSQL_ROOT_PASSWORD=<root password>
#     -v /input:/fragalysis
#     -v /output:/code/media
#     loader:latest
#

FROM xchem/fragalysis-loader:latest

ENV APP_ROOT /code

COPY docker-entrypoint.sh ${APP_ROOT}/
RUN chmod 755 *.sh && \
    chmod 755 *.py

WORKDIR ${APP_ROOT}

# Set entrypont
CMD [ "./docker-entrypoint.sh" ]
