# A dockerfile to build the Image Loader using the latest xchem backend code.
#
# You can build and deploy the loader using docker-compose.
# To load the 2018-10-24T18 stack media data from the directory ../input
# (that contains a 'django_media' directory) to the directory ../output,
# you could add this to your docker-compose.yml file where your stack services
# are defined: -
#
#  loader:
#    build:
#      context: .
#      dockerfile: Dockerfile-local
#    image: loader:latest
#    volumes:
#      - ../input:/fragalysis
#      - ../output:/code/media
#    environment:
#      DATA_ORIGIN: 2018-10-24T18
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: django_db
#      MYSQL_PASSWORD: django_password
#      MYSQL_USER: django
#    depends_on:
#      - mysql
#
# And then to build and run (in detached mode): -
#
#   docker-compose up --build -d

FROM xchem/fragalysis-loader:latest

ENV APP_ROOT /code

COPY docker-entrypoint.sh ${APP_ROOT}/
RUN chmod 755 *.sh

WORKDIR ${APP_ROOT}

CMD [ "./docker-entrypoint.sh" ]
