---

# The Fragalysis Stack Loader Job Template.
#
# This us used by the Jenkins Ci/CD framework to delet and launch
# loader Jobs.
#
# oc process -f fs-loader.yaml | oc create -f -
# oc delete job --selector template=fs-loader

kind: Template
apiVersion: v1
metadata:
  name: fs-loader
labels:
  template: fs-loader

parameters:

- name: BUSYBOX_IMAGE
  value: busybox:1.28.0

- name: LOADER_NAMESPACE
  value: fragalysis-cicd
- name: LOADER_REGISTRY
  value: docker-registry.default.svc:5000
- name: LOADER_IMAGE
  value: fragalysis-cicd/loader-stream
- name: LOADER_IMAGE_TAG
  value: latest

objects:

# -----------------------------------------------------------------------------
# Fragalysis Loader (Job)
# -----------------------------------------------------------------------------

- kind: Job
  apiVersion: batch/v1
  metadata:
    name: fs-loader
    namespace: ${LOADER_NAMESPACE}
  spec:
    template:
      metadata:
        name: fs-loader
      spec:
        # Init Containers
        initContainers:
        - image: ${BUSYBOX_IMAGE}
          name: wait-for-db
          command:
          - 'sh'
          - '-c'
          - 'until nslookup mysql; do echo waiting for db; sleep 1; done;'

        containers:
        - image: ${LOADER_REGISTRY}/${LOADER_IMAGE}:${LOADER_IMAGE_TAG}
          name: fs-loader
          command:
          - 'sh'
          - '-c'
          - './docker-entrypoint.sh'
          env:
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database-host
          - name: MYSQL_PORT
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database-port
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database-password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database-root-password
          volumeMounts:
          - name: fs-web-media-data
            mountPath: /code/media
          - name: fs-input
            mountPath: /fragalysis
        volumes:
        - name: fs-web-media-data
          persistentVolumeClaim:
            claimName: fs-web-media-data-claim
        - name: fs-input
          persistentVolumeClaim:
            claimName: fs-input-claim

        restartPolicy: OnFailure
