---

# The Fragalysis Stack Loader Job Template.
#
# This us used by the Jenkins CI/CD framework when deleting and launching
# loader Jobs.
#
# oc process -f fs-loader.yaml | oc create -f -
# oc delete job --selector template=fs-loader

kind: Template
apiVersion: v1
metadata:
  name: fs-loader
labels:
  template: fs-loader

parameters:

- name: BUSYBOX_IMAGE
  value: busybox:1.28.0

- name: LOADER_NAMESPACE
  value: fragalysis-dev
- name: LOADER_REGISTRY
  value: docker-registry.default.svc:5000
- name: LOADER_IMAGE
  value: fragalysis-cicd/loader-stream:latest
- name: LOADER_INPUT_VOLUME_CLAIM_NAME
  value: fs-input-claim
- name: LOADER_MEDIA_VOLUME_CLAIM_NAME
  value: fs-web-media-claim

objects:

# -----------------------------------------------------------------------------
# Fragalysis Loader (Job)
# -----------------------------------------------------------------------------

- kind: Job
  apiVersion: batch/v1
  metadata:
    name: fs-loader
    namespace: ${LOADER_NAMESPACE}
  spec:
    template:
      metadata:
        name: fs-loader
      spec:
        nodeSelector:
          purpose: 'graph'
        serviceAccountName: diamond

        # Init Containers
        initContainers:
        - image: ${BUSYBOX_IMAGE}
          name: wait-for-db
          command:
          - 'sh'
          - '-c'
          - 'until nslookup ${MYSQL_HOST}; do echo waiting for db; sleep 1; done;'
          env:
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database-host

        containers:
        - image: ${LOADER_REGISTRY}/${LOADER_IMAGE}
          name: fs-loader
          imagePullPolicy: Always
          command:
          - 'sh'
          - '-c'
          - './docker-entrypoint.sh'
          env:
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database-host
          - name: MYSQL_PORT
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database-port
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database-password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fs-mysql-secrets
                key: database-root-password
          volumeMounts:
          - name: fs-web-media
            mountPath: /code/media
          - name: fs-input
            mountPath: /fragalysis
        volumes:
        - name: fs-web-media
          persistentVolumeClaim:
            claimName: ${LOADER_MEDIA_VOLUME_CLAIM_NAME}
        - name: fs-input
          persistentVolumeClaim:
            claimName: ${LOADER_INPUT_VOLUME_CLAIM_NAME}

        restartPolicy: Never
