---

- name: Restart MUNGE
  service:
    name: munge
    state: restarted

- name: Restart NFS
  service:
    name: nfs
    state: restarted

- name: Restart slurm
  service:
    name: slurmctl
    state: restarted
