---

# Create the Backup PV

- name: Check Backup PV
  shell: oc get pv
  register: bu_pv
  when: use_nfs
  changed_when: False

- name: Create Backup PV
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-db-backup-pv-nfs.yaml
    -p BACKUP_NAMESPACE={{ namespace }}
    -p BACKUP_PV_DIR={{ backup_nfs_dir }}
    -p BACKUP_VOLUME_NAME={{ backup_vol_name }}
    | oc create -f -
  when:
  - use_nfs
  - backup_vol_name not in bu_pv.stdout

# Create the Backup PVCs

- name: Check Backup PVC
  shell: oc get pvc
  register: bu_pvc
  changed_when: False

- name: Create Backup PVC
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-db-backup-pvc.yaml
    -p BACKUP_VOLUME_NAME={{ backup_vol_name }}
    | oc create -f -
  when: '"fs-db-backup-claim" not in bu_pvc.stdout'

# Create the Backup Deployment

- name: Check Backup Deployment
  shell: oc get cronjobs
  register: bu_cj
  when: deploy_backup
  changed_when: False

- name: Create Backup Deployment (H)
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-db-backup-h.yaml
    | oc create -f -
  when:
  - not enable_rsync_in_backup
  - '"db-backup-hourly" not in bu_cj.stdout'

- name: Create Backup Deployment (H+RSYNC)
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-db-backup-h-plus-rsync.yaml
    | oc create -f -
  when:
  - enable_rsync_in_backup
  - '"db-backup-hourly" not in bu_cj.stdout'

- name: Create Backup Deployment (DWM)
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-db-backup-dwm.yaml
    | oc create -f -
  when: '"db-backup-daily" not in bu_cj.stdout'

# We don't wait for this job,
# its deployment is controlled by Cron.
