---

# Create the Graph PV

- name: Check MolPort Graph PV
  shell: oc get pv
  register: molport_pv
  when:
  - use_nfs
  - deploy_molport_graph
  changed_when: False

- name: Create MolPort Graph PV
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-graph-molport-pv-nfs.yaml
    -p GRAPH_NAMESPACE={{ namespace }}
    | c create -f -
  when:
  - use_nfs
  - deploy_molport_graph
  - '"fs-graph-molport-data" not in molport_pv.stdout'

# Create the Graph PVCs

- name: Check MolPort Graph PVC
  shell: oc get pvc
  register: molport_pvc
  when: deploy_molport_graph
  changed_when: False

- name: Create Jun2018 Graph PVC
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-graph-molport-pvc.yaml
    | oc create -f -
  when:
  - deploy_molport_graph
  - '"fs-graph-molport-data-claim" not in molport_pvc.stdout'

# Create the Graph Deployment

- name: Check MolPort Graph Deployment
  shell: oc get deploymentconfigs
  register: molport_dc
  when: deploy_molport_graph
  changed_when: False

- name: Create MolPort Graph Deployment
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-graph-molport.yaml
    | oc create -f -
  when:
  - deploy_molport_graph
  - '"graph-molport" not in molport_dc.stdout'
