---

- name: Copy origin file
  shell: "cp {{ efs_mount }}/{{ graph_origin }} {{ efs_mount }}/origin.smi"

# Start the nextflkow process using nohup.
# We need to sleep for a while because ssh shell will disconnect to quickly,
# that job scheduler will have no time to start our nohup process.
#
# Thanks to https://ansibledaily.com/execute-detached-process-with-ansible/
#- name: Start Nextflow Master
#  raw: >-
#    cd {{ efs_mount }};
#    nohup ~/nextflow run graph.nf
#        -executor.queueSize {{ nf_q_size }}
#        -process.executor ignite
#        -process.scratch
#        -with-docker busybox
#        -with-report
#        -with-trace
#        -with-timeline
#        -cluster.join path:{{ efs_mount }}/cluster </dev/null >/dev/null 2>&1 &
#        sleep 4
