---

# A play that sets the 'nextflow_is_running' boolean fact.
#
# It does this ny inspecting the content of the '.nextflow.log' (if it exists).
# If the end of the file does not contain the 'Goodbye' text hen nextflow is
# considered to be running. nextflow is not running if the file does not exist
# or it exists and the 'Goodbye' text can be found.

- name: Check nextflow logfile
  stat:
    path: "{{ workflow_path }}/.nextflow.log"
  register: nextflow_log_file

- name: Inspect end of log
  shell: >-
    tail -n 3 {{ workflow_path }}/.nextflow.log
    | grep "Execution complete -- Goodbye"
    | wc -l
  register: nextflow_log_tail
  when: nextflow_log_file.stat.exists

- name: Set 'is running' fact
  set_fact:
    nextflow_is_running: "{{ nextflow_log_file.stat.exists and nextflow_log_tail|int == 0 }}"

- name: Display 'is running' fact
  debug:
    var: nextflow_is_running
