---

# Deduplicate results.
#
# This play attempts to de-duplicates nodes and edges
# (unless they're already de-duplicated). It then reports on the
# respective file sizes and then compresses the resultant txt files.
# It is an error if there are no nodes or edges.

# Deduplicate Nodes

- name: Check compressed Nodes
  stat:
    path: "{{ dedupe_path }}/nodes.txt.gz"
  register: nodes_gz_file

- name: Deduplicate Nodes
  shell: >-
    zcat *.nodes.gz
    | sort -S16G --parallel=16 --temporary-directory=. -u
    > {{ dedupe_path }}/nodes.txt
  environment:
    LC_ALL: C
  args:
    chdir: "{{ process_path }}/results"
  when: not nodes_gz_file.stat.exists

- name: Collect node count
  shell: cat {{ dedupe_path }}/nodes.txt | wc -l
  register: nodes_lines
  environment:
    LC_ALL: C
  when: not nodes_gz_file.stat.exists

- name: Report node count
  debug:
    msg: Node count is {{ nodes_lines.stdout }}
  when: not nodes_gz_file.stat.exists

- name: Assert we have nodes
  assert:
    that:
    - nodes_lines.stdout|int > 0
    msg: There are no NODES in the compressed file
  when: not nodes_gz_file.stat.exists

# Deduplicate Edges

- name: Check compressed Edges
  stat:
    path: "{{ dedupe_path }}/edges.txt.gz"
  register: edges_gz_file

- name: Deduplicate Edges
  shell: >-
    zcat *.edges.gz
    | sort -S16G --parallel=16 --temporary-directory=. -u
    > {{ dedupe_path }}/edges.txt
  environment:
    LC_ALL: C
  args:
    chdir: "{{ process_path }}/results"
  when: not edges_gz_file.stat.exists

- name: Collect edge count
  shell: cat {{ dedupe_path }}/edges.txt | wc -l
  register: edges_lines
  environment:
    LC_ALL: C
  when: not edges_gz_file.stat.exists

- name: Report edge count
  debug:
    msg: Edge Count is {{ edges_lines.stdout }}
  when: not edges_gz_file.stat.exists

- name: Assert we have edges
  assert:
    that:
    - edges_lines.stdout|int > 0
    msg: There are no EDGES in the compressed file
  when: not edges_gz_file.stat.exists

# Compress ...

- name: Compress
  shell: gzip {{ tgt }}
  environment:
    LC_ALL: C
  args:
    creates: "{{ tgt }}.gz"
  vars:
    tgt: "{{ dedupe_path }}/{{ item }}.txt"
  loop:
  - nodes
  - edges
