---

# Deduplicate results

- name: Create temporary directory
  file:
    path: /tmp
    state: directory

- name: Deduplicate
  shell: >-
    zcat *.{{ item }}.gz
    | sort -S16G --parallel=16 --temporary-directory=/tmp -u > {{ tgt }}
  environment:
    LC_ALL: C
  args:
    creates: "{{ tgt }}"
    chdir: "{{ lookup('env','HOME') }}/{{ process_dir }}/results"
  vars:
    tgt: "{{ lookup('env','HOME') }}/{{ item }}.txt"
  loop:
  - attributes
  - nodes
  - edges
