---

# Deduplicate results.
#
# This play attempts to de-duplicates attributes, nodes and edges
# (unless they're already de-duplicated). It them reports on the
# respective file sizes and then compresses the resultant txt files.

# Deduplicate Nodes

- name: Check compressed Nodes
  stat:
    path: "{{ dedupe_path }}/nodes.txt.gz"
  register: nodes_gz_file

- name: Deduplicate Nodes
  shell: >-
    zcat *.nodes.gz
    | sort -S16G --parallel=16 --temporary-directory={{ tmp_path }} -u
    > {{ dedupe_path }}/nodes.txt
  environment:
    LC_ALL: C
  args:
    chdir: "{{ process_path }}/results"
  when: not nodes_gz_file.stat.exists

- name: Collect node count
  shell: wc -l {{ dedupe_path }}/nodes.txt
  register: nodes_lines
  environment:
    LC_ALL: C
  when: not nodes_gz_file.stat.exists

- name: Display node count
  debug:
    var: nodes_lines.stdout
  when: not nodes_gz_file.stat.exists

# Deduplicate Edges

- name: Check compressed Edges
  stat:
    path: "{{ dedupe_path }}/edges.txt.gz"
  register: edges_gz_file

- name: Deduplicate Edges
  shell: >-
    zcat *.edges.gz
    | sort -S16G --parallel=16 --temporary-directory={{ tmp_path }} -u
    > {{ dedupe_path }}/edges.txt
  environment:
    LC_ALL: C
  args:
    chdir: "{{ process_path }}/results"
  when: not edges_gz_file.stat.exists

- name: Collect edge count
  shell: wc -l {{ dedupe_path }}/edges.txt
  register: edges_lines
  environment:
    LC_ALL: C
  when: not edges_gz_file.stat.exists

- name: Display edge count
  debug:
    var: edges_lines.stdout
  when: not edges_gz_file.stat.exists

# Compress ...

- name: Compress
  shell: gzip {{ tgt }}
  environment:
    LC_ALL: C
  args:
    creates: "{{ tgt }}.gz"
  vars:
    tgt: "{{ dedupe_path }}/{{ item }}.txt"
  loop:
  - attributes
  - nodes
  - edges
