---

# All the things to do when the processing is complete.
#
# This essentially means recording the 'provenance' -
# the files in graph directory that record various repository
# commit references and the parameter file used for processing.
# All the files that should capture the build environment.

- name: Check Process Done File
  stat:
    path: "{{ graph_path }}/done"
  register: process_done_file

- name: Save provenance files (build {{ build_number }})
  shell: ./graph_put_build_provenance_files.py {{ graph_path }} {{ path }}
  args:
    chdir: "{{ scripts }}"
  environment:
    FRAGALYSIS_S3_BUCKET: "{{ s3_bucket }}"
  vars:
    path: "{{ process_path }}/build-{{ build_number }}"
  when:
  - process_done_file.stat.exists
  - s3_write|bool

# Clean-up?
#
# This step removes the working directories,
# providing valuable free-space on the control host.

- name: Clean up
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ dedupe_path }}"
    - "{{ workflow_path }}"
    - "{{ graph_path }}"
    - "{{ tmp_path }}"
  become: yes
  when: clean_finish|bool
