---

# All the things to do when the processing is complete.
#
# This essentially means recording the 'provenance' -
# te in the build directory that record various repository
# commit references and the parameter file used for processing.

- name: Preserve graph provenance
  aws_s3:
    bucket: "{{ fragalysis_bucket }}"
    object: "build/{{ process_path }}/build-{{ build_number }}/{{ item }}"
    src: "{{ graph_path }}/{{ item }}"
    mode: put
  loop:
  - "dls-commit.ref"
  - "fragalysis_commit.ref"
  - "standard.ref"
  - "parameters.ref"
