---

# Gets the standard file from the S3 bucket.
# This uses the script (a Python module) in the fragalysis repo.

- name: Check variables
  assert:
    that:
    - fragalysis_bucket is defined
    - fragalysis_bucket|length > 0
    - fragalysis_standard is defined
    - fragalysis_standard|length > 0
    - aws_access_key_id is defined
    - aws_access_key_id|length > 0
    - aws_secret_access_key is defined
    - aws_secret_access_key|length > 0
    msg: Have you defined all the required environment variables?

- name: Get standard
  shell: >-
    {{ scripts }}/graph_get_standard_file.py
    {{ fragalysis_standard }}
    {{ lookup('env','HOME') }}/{{ process_dir }}

- name: Install nextflow files
  copy:
    src: graph-from-standard.nf
    dest: "{{ lookup('env','HOME') }}/{{ process_dir }}"
