---

# Gets the standard file from the S3 bucket.
# This uses the script (a Python module) in the fragalysis repo.

- name: Check nextflow
  shell: echo -n $(pgrep java)
  register: nextflow_result

- name: Assert nextflow is not running
  assert:
    that:
    - nextflow_result.stdout|length == 0
    msg: Nextflow appears to be running!

- name: Get standard file
  shell: >-
    {{ scripts }}/graph_get_standard_file.py
    {{ fragalysis_path }}/standard-{{ fragalysis_standard_number }}
    {{ lookup('env','HOME') }}/{{ process_dir }}
    --force
