---

- name: Check nextflow
  shell: echo -n $(pgrep nextflow)
  register: nextflow_result

- name: Install nextflow files
  copy:
    src: graph-from-standard.nf
    dest: "{{ lookup('env','HOME') }}/{{ process_dir }}"
  when: nextflow_result.stdout|length == 0
