---

- name: Set path facts
  set_fact:
    dedupe_path: "{{ lookup('env', 'HOME') }}/{{ dedupe_dir }}"
    graph_path: "{{ lookup('env', 'HOME') }}/{{ graph_dir }}"
    workflow_path: "{{ lookup('env','HOME') }}/{{ gp_workflow_dir }}"
    tmp_path: "{{ tmp_dir }}"

# Clean-up before the run...
# The following task does not run if 'clean_start' is false.

- name: Remove existing directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - "{{ dedupe_path }}"
  - "{{ workflow_path }}"
  - "{{ graph_path }}"
  - "{{ tmp_path }}"
  become: yes
  when: clean_start|bool

# Now ensure that the working directories exist
# and write some provenance information to the graph directory
# (which will eventually be uploaded to S3)

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ workflow_path }}"
  - "{{ dedupe_path }}"
  - "{{ graph_path }}"
  - "{{ tmp_path }}"

- name: Get a build number
  shell: ./graph_get_unused_build_number.py {{ process_id }}
  args:
    chdir: "{{ scripts }}"
  environment:
    FRAGALYSIS_S3_BUCKET: "{{ s3_bucket }}"
  register: build_no_result
  changed_when: false

- name: Show build number
  debug:
    msg: "{{ build_no_result.stdout }}"

- name: Set dynamic facts (Build)
  set_fact:
    build_number: "{{ build_no_result.stdout|int }}"

- name: Collect environment
  shell: env
  register: env_result

# Create 'provenance' files...

- name: Write DLS commit provenance
  copy:
    content: "{{ dls_commit_ref }}"
    dest: "{{ graph_path }}/dls-commit.prov"

- name: Write Fragalysis commit provenance
  copy:
    content: "{{ fragalysis_commit_ref }}"
    dest: "{{ graph_path }}/fragalysis_commit.prov"

- name: Write standard provenance
  copy:
    content: "{{ process_id }}/standard-{{ process_standard_number }}"
    dest: "{{ graph_path }}/standard.prov"

- name: Write enviornment provenance
  copy:
    content: "{{ env_result.stdout }}"
    dest: "{{ graph_path }}/env.prov"

- name: Copy playbook parameter file
  copy:
    src: "{{ role_path }}/../../parameters"
    dest: "{{ graph_path }}/parameters.prov"
