---

# Just run these plays...

- import_tasks: sanity-check.yaml

- import_tasks: preamble.yaml

- import_tasks: get-standard-file.yaml
- import_tasks: get-nextflow-file.yaml
- import_tasks: run-nextflow.yaml
  when: nextflow_run
