---

# Just run these plays...

- import_tasks: sanity-check.yaml

- import_tasks: preamble.yaml

- import_tasks: get-standard-file.yaml
- import_tasks: get-nextflow-file.yaml
- import_tasks: run-nextflow.yaml
  when: nextflow_run|bool
- import_tasks: deduplicate.yaml
- import_tasks: txt-to-csv.yaml
- import_tasks: cleanup.yaml
  when: clean_up|bool
