---

# Tasks that run prior to any graph processing.
#
# The commit reference of the dls_fragalysis_stack_openshift repo
# (from where ansible is executed) is written to 'dls-commit-ref'
# in the process directory. This is used to keep a record of precisely
# what was executed.

- name: Check nextflow
  shell: nextflow -version
  register: nf_v_result
  changed_when: false

- name: Display nextflow version
  debug:
    var: nf_v_result

- name: Get DLS commit reference
  shell: git log --pretty=format:'%h' -n 1
  register: commit_result

- name: Set salient facts
  set_fact:
    dls_commit_ref: "{{ commit_result.stdout }}"
    dedupe_path: "{{ lookup('env', 'HOME') }}/{{ dedupe_dir }}"
    output_path: "{{ lookup('env', 'HOME') }}/{{ output_dir }}"
    process_path: "{{ lookup('env','HOME') }}/{{ process_dir }}"
    tmp_path: "{{ lookup('env', 'HOME') }}/tmp"

# Clean-up before the run (excluding the tmp directory)...

- name: Remove existing directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
  - "{{ dedupe_path }}"
  - "{{ process_path }}"
  - "{{ output_path }}"
  become: yes
  when: clean_up|bool
