---

# Tasks that run prior to any graph processing.
#
# The commit reference of the dls_fragalysis_stack_openshift repo
# (from where ansible is executed) is written to 'dls-commit-ref'
# in the process directory. This is used to keep a record of precisely
# what was executed.

- name: Set path facts
  set_fact:
    dedupe_path: "{{ lookup('env', 'HOME') }}/{{ dedupe_dir }}"
    graph_path: "{{ lookup('env', 'HOME') }}/{{ graph_dir }}"
    workflow_path: "{{ lookup('env','HOME') }}/{{ workflow_dir }}"

- name: Check nextflow
  shell: nextflow -version
  register: nf_v_result
  changed_when: false

- name: Display nextflow version
  debug:
    msg: "{{ nf_v_result.stdout_lines }}"

- name: Get DLS commit reference
  shell: git log --pretty=format:'%h' -n 1
  register: commit_result

- name: Get a build number
  shell: ./graph_get_unused_build_number.py {{ process_path }}
  args:
    chdir: "{{ scripts }}"
  register: build_no_result
  changed_when: false

- name: Show build number
  debug:
    msg: "{{ build_no_result.stdout }}"

- name: Set dynamic facts
  set_fact:
    dls_commit_ref: "{{ commit_result.stdout }}"
    build_number: "{{ build_no_result.stdout|int }}"
