---

# Processes de-duplicated senp7 data files.
# Graph process, de-duplication and txt-to-csv is expected to have taken place.
#
# Here we create a directory (where the processed files will be placed)
# followed by the graph file format processing,
# which creates neo4j compliant files.

- import_tasks: sanity-check.yaml

# Processing (csv -> graph)

- name: Check Process Done File (senp7)
  stat:
    path: "{{ output_path }}/done"
  register: p_done_file

- name: Process (senp7)
  shell: >-
    ./process_senp7_compounds.py
    {{ vendor_file }}  {{ nodes_file }} {{ output }}
    --limit {{ process_limit }}
  args:
    chdir: "{{ scripts }}"
  vars:
    vendor_file: "{{ process_path }}/standardised-compounds.tab.gz"
    nodes_file: "{{ dedupe_path }}/nodes.csv.gz"
    output: "{{ output_path }}"
  when: not p_done_file.stat.exists or not pp_done_file.stat.exists
