---

- name: Check nextflow
  shell: echo -n $(pgrep java)
  register: nextflow_result

- name: Set nextflow command
  set_fact:
    nextflow_cmd: >-
      nextflow run graph-from-standard.nf
      -with-docker busybox
      --limit {{ process_limit }}
      --skip {{ process_skip }}
      -executor.queueSize {{ nextflow_queue_size }}
      {{ nextflow_extra_args }}
      -with-report
      -with-trace
      -with-timeline

- name: Display nextflow command
  debug:
    var: nextflow_cmd

- name: Run nextflow (async)
  command: "{{ nextflow_cmd }}"
  args:
    chdir: "{{ process_path }}"
  async: "{{ nextflow_timeout_minutes|int * 60 }}"
  poll: 0
  register: nextflow_async
  when: nextflow_result.stdout|length == 0

# Optionally wait for nextflow, polling at a user-defined interval...

- name: Wait for nextflow
  async_status:
    jid: "{{ nextflow_async.ansible_job_id }}"
  register: nextflow_result
  until: nextflow_result.finished
  delay: "{{ nextflow_poll_period_minutes|int * 60 }}"
  retries: "{{ (nextflow_timeout_minutes|int / nextflow_poll_period_minutes|int)|int }}"
  when: nextflow_wait
