---

- name: Check nextflow
  shell: echo -n $(pgrep java)
  register: nextflow_result

- name: Run nextflow (nohup)
  shell: >-
    nohup nextflow run graph-from-standard.nf
    -with-docker busybox
    -executor.queueSize {{ nextflow_queue_size }}
    {{ nextflow_extra_args }}
    -with-report
    -with-trace
    -with-timeline
    </dev/null >/dev/null 2>&1 &
  args:
    chdir: "{{ lookup('env','HOME') }}/{{ process_dir }}"
  when: nextflow_result.stdout|length == 0

# Optionally wait for nextflow, polling at 15-minute intervals.
# After pausing for a short time to give nextflow a chance to run.

- name: Pre-exit pause
  pause:
    seconds: 10
  when: nextflow_wait

- name: Wait for nextflow
  shell: echo -n $(pgrep java)
  args:
    chdir: "{{ lookup('env','HOME') }}/{{ process_dir }}"
  delay: 60
  retries: "{{ nextflow_timeout_minutes | int }}"
  register: result
  until: result|length == 0
  when: nextflow_wait
