---

# A play that simply checks that sensible and essential variables
# have been setup. Without these key plays cannot run.

- name: Check variables
  assert:
    that:
    - fragalysis_bucket is defined
    - fragalysis_bucket|length > 0
    - fragalysis_path is defined
    - fragalysis_path|length > 0
    - fragalysis_standard_number is defined
    - fragalysis_standard_number|int > 0
    - fragalysis_build_number is defined
    - fragalysis_build_number|int > 0
    - aws_access_key_id is defined
    - aws_access_key_id|length > 0
    - aws_secret_access_key is defined
    - aws_secret_access_key|length > 0
    msg: Have you defined all the required environment variables?

# The 'check' utility returns a string ('present' or 'absent')

- name: Check build target
  shell: ./graph_check_path.py {{ build_path }}
  args:
    chdir: "{{ scripts }}"
  vars:
    build_path: build/{{ fragalysis_path }}/build-{{ fragalysis_build_numbe }}
  register: build_check_result

- name : echo
  debug:
    msg: "{{ build_check_result }}"
- name: Assert build target is free
  assert:
    that:
    - build_check_result.stdout == 'absent'
  msg: The build already exists, you need to use a new build number
