---

# A play that simply checks that sensible and essential variables
# have been setup. Without these key plays cannot run.

- name: Check variables
  assert:
    that:
    - fragalysis_bucket is defined
    - fragalysis_bucket|length > 0
    - process_path is defined
    - process_path|length > 0
    - process_standard_number is defined
    - process_standard_number|int > 0
    - aws_access_key_id is defined
    - aws_access_key_id|length > 0
    - aws_secret_access_key is defined
    - aws_secret_access_key|length > 0
    msg: Have you defined all the required environment variables?
