---

# Processes de-duplicated txt files into csv, saving those to S3.
# Graph process and de-duplication is expected to have taken place.
#
# Here we create a directory (where the processed files will be placed)
# and then do some pre-processing (turning .txt.gz into .csv.gz)
# followed by the final processing, which creates neo4j compliant files.

- import_tasks: sanity-check.yaml

# Process preparation (txt -> csv)

- name: Check TXT-CSV Done File
  stat:
    path: "{{ dedupe_path }}/done"
  register: csv_done_file

- name: TXT to CSV
  shell: ./process_prep.py {{ input }} {{ output }}
  args:
    chdir: "{{ scripts }}"
  vars:
    input: "{{ dedupe_path }}"
    output: "{{ dedupe_path }}"
  when: not csv_done_file.stat.exists

# Commit build files to the S3 bucket
# But only run if the prior step ran
# (i.e. if the done file did not initially exist)

- name: Check TXT-CSV Done File
  stat:
    path: "{{ dedupe_path }}/done"
  register: csv_done_file

- name: Save TXT and CSV (build {{ build_number }})
  shell: ./graph_put_build_files.py {{ input }} {{ output }}
  args:
    chdir: "{{ scripts }}"
  vars:
    input: "{{ dedupe_path }}"
    output: "{{ process_id }}/build-{{ build_number }}"
  environment:
    FRAGALYSIS_S3_BUCKET: "{{ s3_bucket }}"
  when:
  - csv_done_file.stat.exists
  - s3_write|bool
