---

- name: Make directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ lookup('env','HOME') }}/github"

- name: Clone Fragalysis
  git:
    repo: https://github.com/InformaticsMatters/fragalysis
    version: "{{ fragalysis_version }}"
    dest: "{{ lookup('env','HOME') }}/github/fragalysis"

- name: Install Python requirements
  pip:
    requirements: "{{ lookup('env','HOME') }}/github/fragalysis/requirements.txt"
  become: yes

- name: Remove nextflow
  file:
    path: "{{ lookup('env','HOME') }}/bin/nextflow"
    state: absent
  become: yes

- name: Get nextflow
  uri:
    url: "{{ download }}/v{{ nextflow_version }}/nextflow"
    dest: "{{ lookup('env','HOME') }}/bin/nextflow"
  vars:
    download: https://github.com/nextflow-io/nextflow/releases/download
  become: yes

- name: Allowing nextflow execution
  file:
    dest: "{{ lookup('env','HOME') }}/bin/nextflow"
    mode: a+x
    owner: "{{ ansible_user }}"
  become: yes
