---

aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

fragalysis_bucket: "{{ lookup('env', 'FRAGALYSIS_S3_BUCKET') }}"
fragalysis_standard: activity/senp7/standard-2

# Nextflow config.
# Timeouts:  2880 (2 days)
#           10080 (7 days)
nextflow_extra_args: -process.scratch
nextflow_queue_size: 16
nextflow_timeout_minutes: 10080
nextflow_run: yes
nextflow_wait: yes

process_dir: process
output_dir: output

# Limit processing (0 implies no limit)
process_limit: 0

scripts: "{{ lookup('env','HOME') }}/github/fragalysis/frag/network/scripts"
pythonpath: "{{ lookup('env','HOME') }}/github/fragalysis"