---

# The graph processing directories,
# which must be different as processes can create a 'done' file
# in the corresponding directory (e.g. for dedupe and graph).
#
# Directories are needed for the nextflow 'workflow',
# the grand 'de-duplication' of the node/edge files and
# the final 'graph' files.
gp_workflow_dir: gp-workflow
dedupe_dir: dedupe
graph_dir: graph

# The poll period for the Nextflow process
gw_nextflow_poll_period_minutes: 20

# Size of an individual processing shred
process_gp_shred_size: 200
# Size of an individual processing chunk
process_gp_chunk_size: 10

# The standard file number to use as a source for the graph processing.
# This standard file is expected to exist for the defined process path.
# So the following file (key) must exist on S3: -
#   {{ s3_bucket }}/standard/{{ process_path }}/
#       standard-{{ process_standard_number }}/standardised-compounds.tab.gz
process_standard_number: 2

# Delete unnecessary nextflow files when nextflow is complete.
# This will include things like the standard file
# and the work directory.
delete_nextflow_as_needed: no
