---

# Setup the Fragalysis (TEST) Project.
# Ths includes the project and its service account.

- name: Login (admin)
  shell: oc login {{ cluster_url }} -u admin -p {{ admin_password }}
  changed_when: False

- name: Get Projects
  shell: oc get projects
  register: projects_result
  changed_when: False

- name: Create Graph Project
  shell: >
    oc new-project {{ graph_1_namespace }}
    --display-name="{{ graph_1_namespace_display_name }}"
    --description="{{ graph_1_namespace_description }}"
  when: graph_1_namespace not in projects_result.stdout

- name: Move to Graph Project
  shell: oc project {{ graph_1_namespace }}
  changed_when: False

- name: Check Diamond Service Account exists
  shell: oc get sa
  register: diamond_sa_result
  changed_when: False

- name: Create Diamond Service Account (Graph Project)
  shell: "{{ item }}"
  loop:
  - oc create sa diamond
  - oc adm policy add-role-to-user admin -z diamond
  - oc adm policy add-scc-to-user anyuid -z diamond
  when: '"diamond" not in diamond_sa_result.stdout'
