---

# Removes the Graph 1 deployment.
# This essentially consists of removing the project (and waiting for it).

- name: Delete Fragalysis GRAPH 1 Environment?
  pause:
    prompt: |-
      Delete the GRAPH-1 environment from {{ cluster_url }}?
      Hit return to delete it.
      Hit Ctrl+c and then "a" if you've changed your mind.

# Go...

- name: Login (admin at {{ cluster_url }})
  shell: oc login {{ cluster_url }} -u admin -p {{ admin_password }}
  changed_when: False

# Remove Graph-2 namespace

- name: Check projects
  shell: oc get projects
  register: p_result
  changed_when: False

- name: Delete Graph-1 project
  shell: oc delete project/{{ graph_1_namespace }}
  when: graph_1_namespace in p_result.stdout

- name: Wait for Graph-1 project deletion
  shell: oc get projects
  register: wait_cmd
  retries: 12
  delay: 10
  until: graph_1_namespace not in wait_cmd.stdout
  changed_when: False
