---

# Install packages for munge, slurm and other stuff

- name: Install stuff
  yum:
    name:
    - epel-release
    - nfs-utils
    - nfs-utils-lib
    - munge
    - openssl
    - numactl
    - hwloc
    - lua
    - libibmad
    - libibumad

# Setup NFS share and head node mounts

- name: Create home
  file:
    path: /home
    state: directory
    mode: 0777
    owner: root
    group: root

- name: Ensure mount has a filesystem
  filesystem:
    fstype: ext4
    dev: "{{ os_slurm_volume_device }}"

- name: Mount home
  mount:
    name: /home
    src: "{{ os_slurm_volume_device }}"
    fstype: auto
    opts: defaults,nobootwait
    passno: 2
    state: mounted

- name: Copy exports
  copy:
    content: /home *(rw,no_root_squash)
    dest: /etc/exports
    owner: root
    group: root
  notify: Restart NFS

# Crete munge and slurm groups and users

- name: Crete munge group
  group:
    gid: "{{ os_munge_user_id }}"
    name: munge

- name: Crete munge user
  user:
    name: munge
    uid: "{{ os_munge_user_id }}"
    group: munge
    home: /var/lib/munge
    shell: /sbin/nologin

- name: Crete slurm group
  group:
    gid: "{{ os_slurm_user_id }}"
    name: slurm

- name: Crete slurm user
  user:
    name: slurm
    uid: "{{ os_slurm_user_id }}"
    group: slurm
    home: /var/lib/slurm
    shell: /bin/bash

# Install munge

- name: Configure munge directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
    owner: munge
    recurse: true
  loop:
  - /etc/munge
  - /var/log/munge

# Setup slurm

- name: Configure slurmd directory
  file:
    path: /var/spool/slurmd
    state: directory
    mode: 0755
    owner: slurm
    recurse: true

- name: Initialise logfile
  file:
    path: /var/log/slurmd.log
    state: touch
    owner: slurm
