---

# Creates our cluster on OpenStack.
#
# This is driven by variables that should be defined by
# 'sourcing' your OpenStack Keystone file. The initial
# 'assert' check that variables appear to be set.

- name: Assert key variables
  assert:
    that:
    - os_auth_url is defined
    - os_worker_count > 0

- name: Create shared volume
  os_volume:
    auth: "{{ os_auth }}"
    size: "{{ os_volume_size_g }}"
    display_name: "{{ os_instance_base_name }}-volume"
    display_description: Shared volume for the Fragment cluster

- name: Create head node
  os_server:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    name: "{{ os_instance_base_name }}-head"
    availability_zone: "{{ os_availability_zone }}"
    image: "{{ os_head_image_name }}"
    flavor: "{{ os_head_flavour }}"
    key_name: "{{ os_key_name }}"
    auto_floating_ip: true

- name: Attach the shared volume to the head node
  os_server_volume:
    auth: "{{ os_auth }}"
    device: "{{ os_volume_device }}"
    server: "{{ os_instance_base_name }}-head"
    volume: "{{ os_instance_base_name }}-volume"

- name: Create worker nodes
  os_server:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    name: "{{ os_instance_base_name }}-worker-{{ '%d'|format(item|int + 1) }}"
    availability_zone: "{{ os_availability_zone }}"
    image: "{{ os_worker_image_name }}"
    flavor: "{{ os_worker_flavour }}"
    key_name: "{{ os_key_name }}"
    auto_floating_ip: false
  loop: "{{ range(os_worker_count)|list }}"
