---

# Deletes our cluster.
#
# On OpenStack this is driven by variables that should be defined by
# 'sourcing' your OpenStack Keystone file. The initial
# 'assert' checks that these variables are set.

- name: Delete Cloud?
  pause:
    prompt: |-
      Are you sure you want to delete the '{{ instance_base_name }}' cloud instances?
      Hit return to delete.
      Hit Ctrl+c and then "a" if you've changed your mind

- name: Assert key variables
  assert:
    that: os_auth_url is defined

# No need to detach the volume
# (we see errors if it's not there anyway)
# so just delete the server...

- name: Delete head node
  os_server:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    name: "{{ instance_base_name }}-head"
    state: absent
  when: provider=='openstack'

- name: Get worker node facts
  os_server_facts:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    server: "{{ instance_base_name }}-worker-*"
  when: provider=='openstack'

- name: Delete worker nodes
  os_server:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    name: "{{ item['name'] }}"
    state: absent
  loop: "{{ openstack_servers }}"
  no_log: yes
  when: provider=='openstack'

- name: Delete shared volume
  os_volume:
    auth: "{{ os_auth }}"
    display_name: "{{ instance_base_name }}-volume"
    state: absent
  when: provider=='openstack'
