---

# Deletes our cluster on OpenStack.
#
# This is driven by variables that should be defined by
# 'sourcing' your OpenStack Keystone file. The initial
# 'assert' check that variables appear to be set.

- name: Assert key variables
  assert:
    that: os_auth_url is defined

# No need to detach the volume
# (we see errors if it's not there anyway)
# so just delete the server...

- name: Delete head node
  os_server:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    name: "{{ slurm_instance_base_name }}-head"
    state: absent

- name: Delete woker nodes
  os_server:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    name: "{{ slurm_instance_base_name }}-worker-{{ '%d'|format(item|int + 1) }}"
    state: absent
  loop: "{{ range(slurm_worker_count)|list }}"

- name: Delete shared volume
  os_volume:
    auth: "{{ os_auth }}"
    display_name: "{{ slurm_instance_base_name }}-volume"
    state: absent
