---

# Deletes our Slurm cluster on OpenStack.
#
# This is driven by variables that should be defined by
# 'sourcing' your OpenStack Keystone file. The initial
# 'assert' check that variables appear to be set.

- name: Assert key variables
  assert:
    that: os_auth_url is defined

# No need to detach the volume
# (we see errors if it's not there anyway)
# so just delete the server...

- name: Delete Slurm head node
  os_server:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    name: frag-slurm-head
    state: absent

- name: Delete Slurm shared volume
  os_volume:
    auth: "{{ os_auth }}"
    size: "{{ os_slurm_volume_size_g }}"
    display_name: frag-volume
    state: absent
