---

- name: Assert key variables
  assert:
    that: os_auth_url is defined

# Get information about the node
# We simply want its IP address
# so we can add it to the 'slurm_head' inventory group

- name: Get head node facts
  os_server_facts:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    server: "{{ slurm_instance_base_name }}-head"

- name: Display head node
  debug:
    var: openstack_servers

- name: Adjust head node group
  add_host:
    groups: slurm_head
    name: "{{ openstack_servers[0].interface_ip }}"

# Get information about the worker nodes
# We simply want their IP addresses
# so we can add them to the 'slurm_worker' inventory group

- name: Get worker node facts
  os_server_facts:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    server: "{{ slurm_instance_base_name }}-worker-*"

- name: Add worker nodes
  add_host:
    groups: slurm_worker
    name: "{{ item.private_v4 }}"
  loop: "{{ openstack_servers }}"

# Get information about the worker node 'flavour'.
# We want the CPU count for slurm.

- name: Get worker node flavour facts
  os_flavor_facts:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    name: "{{ os_worker_flavour }}"

# Now set a 'worker_nodes' fact.
# This contains their names, addresses and vCPU value.

- name: Create worker nodes fact
  set_fact:
    worker_nodes: "{{ nodes|default([]) + [{'addr': item.private_v4, 'name': item.name, 'vcpus': vcpus}] }}"
  vars:
    vcpus: "{{ openstack_flavors[0]['vcpus'] }}"
  loop: "{{ openstack_servers }}"
