---

- name: Assert key variables
  assert:
    that: os_auth_url is defined

# Get information about the node
# We simply want its IP address
# so we can add it to the 'slurm_head' inventory group

- name: Get head node facts
  os_server_facts:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    server: "{{ slurm_instance_base_name }}-head"

- name: Display head node
  debug:
    var: openstack_servers

- name: Adjust head node group
  add_host:
    groups: slurm_head
    name: "{{ openstack_servers[0].interface_ip }}"

# Get information about the worker nodes
# We simply want their IP addresses
# so we can add them to the 'slurm_worker' inventory group
# and set a 'nodes' fact that wil lbe used for application templating.

- name: Get worker node facts
  os_server_facts:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    server: "{{ slurm_instance_base_name }}-worker-*"

- name: Add worker nodes
  add_host:
    groups: slurm_worker
    name: "{{ item.private_v4 }}"
  loop: "{{ openstack_servers }}"

- name: Create nodes list
  set_fact:
    nodes: "{{ nodes|default([]) + [{'addr': item.private_v4, 'name': item.name}] }}"
  loop: "{{ openstack_servers }}"

# Get information about the head and worker node 'flavours'
# We want the CPU count for slurm.

- name: Get head node flavour facts
  os_flavor_facts:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    name: "{{ os_head_flavour }}"

- name: Print head flavour fact
  debug:
    var: openstack_flavors

- name: Get worker node flavour facts
  os_flavor_facts:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    name: "{{ os_worker_flavour }}"

- name: Print worker flavour fact
  debug:
    var: openstack_flavors