---

# Before we continue,
# make sure the user actually wants to create the cloud...

- name: Create Cloud?
  pause:
    prompt: |-
      Are you sure you want to create the '{{ os_instance_base_name }}' cloud instances?
      Hit return to create.
      Hit Ctrl+c and then "a" if you've changed your mind

- import_tasks: create-os-instances.yaml
- import_tasks: gather-os-facts.yaml
