---

# Tasks for all OpenShift/OKD nodes

- name: Install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - wget
    - git
    - unzip
    - net-tools
    - yum-utils
    - bind-utils
    - httpd-tools
    - iptables-services
    - ntp
    - bridge-utils
    - bash-completion
    - kexec-tools
    - sos
    - psacct
    - pyOpenSSL
    - etcd
    - flannel
    - java-1.8.0-openjdk-headless
    - docker-1.13.1
    - atomic
    - NetworkManager
  become: yes

- name: Enable and start docker
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Enable and start NetworkManager
  systemd:
    name: NetworkManager
    enabled: yes
    state: started
  become: yes
