---

# Tasks for all OpenShift/OKD nodes

- name: Install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - wget
    - git
    - unzip
    - net-tools
    - yum-utils
    - bind-utils
    - httpd-tools
    - iptables-services
    - ntp
    - bridge-utils
    - bash-completion
    - kexec-tools
    - sos
    - psacct
    - pyOpenSSL
    - etcd
    - flannel
    - java-1.8.0-openjdk-headless
    - docker-1.13.1
    - atomic
    - NetworkManager
  become: yes

# Additional Bastion system configuration
# here we configure 'dns' by adjusting resolv.conf

- name: Adjust reolv.conf (search)
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^search openstacklocal'
    line: search openstacklocal novalocal
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Adjust reolv.conf (remove existing servers)
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^(nameserver .*)$'
    line: '#\1'
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Adjust reolv.conf (insert localhost nameserver)
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver {{ nameserver }}$'
    line: nameserver {{ nameserver }}
    insertafter: '^search '
    owner: root
    group: root
    mode: 0644
  become: yes

# Enable and start some key services...

- name: Enable and start docker
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

# Set SSH public key

- name: Adjust authorised keys
  authorized_key:
    user: "{{ authorized_user }}"
    key: "{{lookup('file', authorized_user_public_key) }}"

# Create the docker group
# and enable docker use from the authorised user

- name: Create docker group
  group:
    name: docker
  notify:
  - Restart docker
  become: yes

- name: Add {{ authorized_user }} to docker group
  user:
    name: "{{ authorized_user }}"
    group: docker
    append: yes
  become: yes

- include_tasks: check.yaml
