---

# Include variables from the role's vars directory
# based on first file found principle...

- name: Gather OS-Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_distribution }}.yaml"
  - default.yaml

# Create some useful directories
# and install a few key Python requirements (mainly to deal with S3)...

- name: Make directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ lookup('env','HOME') }}/{{ github_dir }}"
  - "{{ lookup('env','HOME') }}/bin"

- name: Install Python requirements ({{ pip_executable }})
  pip:
    executable: "{{ pip_executable }}"
    name:
    - boto3==1.9.106
    - botocore==1.12.106

- name: Get DLS commit reference
  shell: git log --pretty=format:'%h' -n 1
  register: commit_result

- name: Set dynamic facts (DLS)
  set_fact:
    dls_commit_ref: "{{ commit_result.stdout }}"

# Configure a fragalysis clone...

- name: Clone Fragalysis
  git:
    repo: https://github.com/InformaticsMatters/fragalysis
    version: "{{ fragalysis_version }}"
    dest: "{{ lookup('env','HOME') }}/{{ github_dir }}/fragalysis"

- name: Get Fragalysis commit reference
  shell: git log --pretty=format:'%h' -n 1
  args:
    chdir: "{{ lookup('env','HOME') }}/{{ github_dir }}/fragalysis"
  register: fragalysis_commit_result

- name: Set Fragalysis Facts
  set_fact:
    fragalysis_commit_ref: "{{ fragalysis_commit_result.stdout }}"
