---

# A play that simply checks that essential variables
# have been setup. Without these key plays cannot run.

- name: Check variables (normally driven by enviornment)
  assert:
    that:
    - s3_bucket is defined
    - s3_bucket|length > 0
    - aws_access_key_id is defined
    - aws_access_key_id|length > 0
    - aws_secret_access_key is defined
    - aws_secret_access_key|length > 0
    msg: Have you defined all the required environment variables?
