---

# The Application's Persistent Volume Claims.
#
# oc process -f fs-db-backup-pvc.yaml | oc create -f -
# oc delete pvc --selector template=fs-db-backup-pvc

kind: Template
apiVersion: v1
metadata:
  name: fs-db-backup-pvc
  annotations:
    description: Fragalysis Stack's Persistent Volume Claims
    tags: fragalysis,db,postgres
labels:
  template: fs-db-backup-pvc

parameters:

- name: BACKUP_NAMESPACE
  value: fragalysis-cicd
- name: BACKUP_PV_BACKUP_SIZE
  value: 100Gi

objects:

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: fs-pg-data-backup-claim
    namespace: ${BACKUP_NAMESPACE}
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${BACKUP_PV_BACKUP_SIZE}
