---

# The Fragalysis Stack's Neo4J Graph database deployment.
#
# oc process -f fs-db.yaml | oc create -f -
# oc delete all --selector template=fs-db

kind: Template
apiVersion: v1
metadata:
  name: fs-db
  annotations:
    description: Fragalysis Stack's Postgres Definition
    tags: fragalysis,db,postgres
labels:
  template: fs-db

parameters:

- name: DB_NAMESPACE
  value: fragalysis-stack

- name: PG_TAG
  value: 9.6.7
- name: PG_REPLICAS
  value: '1'

objects:

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: db
    namespace: ${DB_NAMESPACE}
  spec:
    replicas: ${PG_REPLICAS}
    selector:
      name: db
    template:
      metadata:
        labels:
          name: db
      spec:
#        serviceAccountName: diamond
        # Application containers
        containers:
        - image: postgres:${PG_TAG}
          name: db
          ports:
          - containerPort: 5432
          readinessProbe:
            initialDelaySeconds: 20
            timeoutSeconds: 1
            tcpSocket:
              port: 5432
          livenessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 30
            tcpSocket:
              port: 5432
          volumeMounts:
          - name: fs-pg-data
            mountPath: /var/lib/postgresql/data
        volumes:
        - name: fs-pg-data
          persistentVolumeClaim:
            claimName: fs-pg-data-claim
        restartPolicy: Always

- kind: Service
  apiVersion: v1
  metadata:
    name: db
    namespace: ${DB_NAMESPACE}
  spec:
    ports:
    - name: api
      port: 5432
      targetPort: 5432
    selector:
      name: db
