---

# The Fragalysis Stack's Neo4J Graph database deployment.
#
# oc process -f fs-graph.yaml | oc create -f -
# oc delete all --selector template=fs-graph

kind: Template
apiVersion: v1
metadata:
  name: fs-graph
  annotations:
    description: Fragalysis Stack's Neo4J Definition
    tags: fragalysis,graph,neo4j
labels:
  template: fs-graph

parameters:

- name: GRAPH_NAMESPACE
  value: fragalysis-cicd

- name: GRAPH_TAG
  value: 'latest'
- name: NEO4J_AUTH
  value: none
- name: NEO4J_PAGECACHE
  value: 4G
- name: NEO4J_REPLICAS
  value: '1'

objects:

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: graph-stream
  spec:
    tags:
    - from:
        kind: DockerImage
        name: xchem/graph:${GRAPH_TAG}
      name: latest
      importPolicy:
        scheduled: true

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: graph
    namespace: ${GRAPH_NAMESPACE}
  spec:
    replicas: ${NEO4J_REPLICAS}
    selector:
      name: graph
    template:
      metadata:
        labels:
          name: graph
      spec:
        serviceAccountName: diamond

        # Application containers
        containers:
        - name: graph
          readinessProbe:
            initialDelaySeconds: 20
            timeoutSeconds: 1
            tcpSocket:
              port: 7474
          livenessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 1
            tcpSocket:
              port: 7474
          env:
          - name: NEO4J_AUTH
            value: ${NEO4J_AUTH}
          - name: NEO4J_dbms_memory_pagecache_size
            value: ${NEO4J_PAGECACHE}
          - name: EXTENSION_SCRIPT
            value: /data-loader/load_neo4j.sh
          ports:
          - containerPort: 7474
          - containerPort: 7687
        restartPolicy: Always

    triggers:
     - type: ConfigChange
     - type: ImageChange
       imageChangeParams:
         automatic: true
         containerNames:
         - graph
         from:
           kind: ImageStreamTag
           name: graph-stream:latest

- kind: Service
  apiVersion: v1
  metadata:
    name: neo4j
    namespace: ${GRAPH_NAMESPACE}
  spec:
    ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687
    selector:
      name: graph
