---

# The Application's CI/CD Persistent Volumes (NFS).
#
# This expects these volumes:
#
#   ${NFS_PATH}/pv-fs-jenkins
#
# oc process -f fs-jenkins-pv-nfs.yaml | oc create -f -
# oc delete pv --selector template=fs-jenkins-nfs

kind: Template
apiVersion: v1
metadata:
  name: fs-jenkins-nfs
  annotations:
    description: Fragalysis Stack's Persistent Volumes (using NFS)
    tags: fragalysis,jenkins
labels:
  template: fs-jenkins-nfs

parameters:

- name: NFS_SERVER
  value: bastion.novalocal
- name: NFS_PATH
  value: /data

- name: JENKINS_NAMESPACE
  value: fragalysis-cicd
- name: JENKINS_PV_DIR
  value: pv-fs-jenkins
- name: JENKINS_PV_SIZE
  value: 10Gi

objects:

# ---------------
# Jenkins Volumes
# ---------------

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: fs-jenkins
  spec:
    capacity:
      storage: ${JENKINS_PV_SIZE}
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/${JENKINS_PV_DIR}
    claimRef:
      name: jenkins
      namespace: ${JENKINS_NAMESPACE}
