---

# The Application's MySQL Persistent Volume Claims.
#
# oc process -f fs-mysql-pvc.yaml | oc create -f -
# oc delete pvc --selector template=fs-mysql-pvc

kind: Template
apiVersion: v1
metadata:
  name: fs-mysql-pvc
  annotations:
    description: Fragalysis Stack's Persistent Volume Claims
    tags: fragalysis,db,postgres
labels:
  template: fs-mysql-pvc

parameters:

- name: MYSQL_NAMESPACE
  value: fragalysis-cicd
- name: MYSQL_PV_SIZE
  value: 20Gi

objects:

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: fs-mysql-data-claim
    namespace: ${MYSQL_NAMESPACE}
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${MYSQL_PV_SIZE}
