---

# The Application's Web Persistent Volume Claims.
#
# oc process -f fs-web-pvc.yaml | oc create -f -
# oc delete pvc --selector template=fs-web-pvc

kind: Template
apiVersion: v1
metadata:
  name: fs-web-pvc
  annotations:
    description: Fragalysis Stack's Persistent Volume Claims
    tags: fragalysis,web,media
labels:
  template: fs-web-pvc

parameters:

- name: WEB_NAMESPACE
  value: fragalysis-cicd
- name: WEB_VOLUME_CLAIM_NAME
  value: fs-web-media-claim
- name: WEB_PV_SIZE
  value: 20Gi

objects:

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${WEB_VOLUME_CLAIM_NAME}
    namespace: ${WEB_NAMESPACE}
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${WEB_PV_SIZE}
