---

# Deploy the project secrets

- name: Check Secrets
  shell: oc get secrets
  register: fs_secrets
  changed_when: False

- name: Create ISPyB Secrets
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-secrets-ispyb.yaml
    -p ISPYB_NAMESPACE={{ namespace }}
    -p ISPYB_USER={{ ispyb_user }}
    -p ISPYB_PASSWORD="{{ ispyb_password }}"
    | oc create -f -
  when: '"fs-ispyb-secrets" not in fs_secrets.stdout'

- name: Create MySQL Secrets
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-secrets-mysql.yaml
    -p MYSQL_NAMESPACE={{ namespace }}
    -p MYSQL_NAME={{ mysql_name }}
    | oc create -f -
  when: '"fs-mysql-secrets" not in fs_secrets.stdout'

- name: Create Graph Secrets
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-secrets-graph.yaml
    -p NAMESPACE={{ namespace }}
    -p GRAPH_BOLT_URL={{ graph_bolt_url }}
    -p GRAPH_SERVICE_NAME={{ graph_svc }}
    | oc create -f -
  when: '"fs-graph-secrets" not in fs_secrets.stdout'

- name: Create Web Secrets
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-secrets-web.yaml
    -p WEB_NAMESPACE={{ namespace }}
    | oc create -f -
  when: '"fs-web-secrets" not in fs_secrets.stdout'
