---

# Deploy the project secrets

- name: Check Secrets
  shell: oc get secrets
  register: fs_secrets
  changed_when: False

- name: Create ISPyB Secrets
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-secrets-ispyb.yaml
    -p ISPYB_USER={{ ispyb_user }}
    -p ISPYB_PASSWORD="{{ ispyb_password }}"
    | oc create -f -
  when: '"fs-ispyb-secrets" not in fs_secrets.stdout'

- name: Create MySQL Secrets
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-secrets-mysql.yaml
    -p MYSQL_NAME={{ mysql_name }}
    | oc create -f -
  when: '"fs-mysql-secrets" not in fs_secrets.stdout'

- name: Create Graph Secrets
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-secrets-graph.yaml
    -p GRAPH_BOLT_URL={{ graph_bolt_url }}
    -p GRAPH_SERVICE_NAME={{ graph_svc }}
    | oc create -f -
  when: '"fs-graph-secrets" not in fs_secrets.stdout'

- name: Create Web Secrets
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-secrets-web.yaml
    | oc create -f -
  when: '"fs-web-secrets" not in fs_secrets.stdout'

- name: Create Backup Secrets
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-secrets-backup.yaml
    -p BACKUP_RSYNC_HOST={{ backup_rsync_host }}
    -p BACKUP_RSYNC_PATH={{ backup_rsync_path }}
    -p BACKUP_RSYNC_USER={{ backup_rsync_user }}
    -p BACKUP_RSYNC_PASS={{ backup_rsync_pass }}
    | oc create -f -
  when:
  - enable_rsync_in_backup
  - '"fs-backup-secrets" not in fs_secrets.stdout'
