---

# Remove the Production project

- name: Check project
  shell: oc get projects
  register: p_result
  changed_when: False

- name: Delete project
  shell: oc delete project/{{ namespace }}
  when: namespace in p_result.stdout

- name: Wait for project deletion
  shell: oc get projects
  register: wait_cmd
  retries: 6
  delay: 10
  until: namespace not in wait_cmd.stdout
  changed_when: False

# Remove Persistent Volumes

- name: Check Persistent Volumes
  shell: oc get pv
  register: pv_result
  changed_when: False

- name: Delete Persistent Volumes
  shell: oc delete pv/{{ item }}
  loop:
  - "{{ mysql_vol_name }}"
  - "{{ backup_vol_name }}"
  - "{{ web_vol_name }}"
  when: item in pv_result.stdout
