---

# Deploy the Web image.
# Which consists of a PV, image stream, PVC and deployment configuration.

# Create the Web PV

- set_fact: web_claim_name={{ web_vol_name }}-claim

- name: Check Web PV
  shell: oc get pv
  register: w_pv
  when: use_nfs
  changed_when: False

- name: Create Web PV
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-web-pv-nfs.yaml
    -p WEB_NAMESPACE={{ namespace }}
    -p WEB_VOLUME_NAME={{ web_vol_name }}
    -p WEB_VOLUME_CLAIM_NAME={{ web_claim_name }}
    -p WEB_MEDIA_PV_DIR={{ web_nfs_dir }}
    | oc create -f -
  when:
  - use_nfs
  - web_vol_name not in w_pv.stdout

# Crete the PVC, Image Stream, Deployment and Route...

- name: Check Web PVC
  shell: oc get pvc
  register: w_pvc
  changed_when: False

- name: Create Web PVC
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-web-pvc.yaml
    -p WEB_NAMESPACE={{ namespace }}
    -p WEB_VOLUME_CLAIM_NAME={{ web_claim_name }}
    | oc create -f -
  when: web_claim_name not in w_pvc.stdout

- name: Wait for Web PVCs to become Bound
  shell: >
    oc get pvc/{{ item }} | grep Bound
  retries: 12
  delay: 5
  register: result
  until: result.rc == 0
  loop:
  - "{{ web_claim_name }}"
  when: item not in w_pvc.stdout
  changed_when: False

- name: Check Web ImageStream
  shell: oc get is
  register: w_is
  changed_when: False

- name: Create ImageStream
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-web-is.yaml
    -p WEB_TAG=stable
    | oc create -f -
  when: '"web-stream" not in w_is.stdout'

- name: Check Web Deployment Config
  shell: oc get dc
  register: w_dc
  changed_when: False

- name: Create Web Deployment Config
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-web.yaml
    -p WEB_NAMESPACE={{ namespace }}
    -p WEB_VOLUME_CLAIM_NAME={{ web_claim_name }}
    -p WEB_HOSTNAME={{ web_hostname }}
    -p WEB_GRAPH_URL={{ graph_url }}
    -p WEB_GRAPH_SERVICE={{ graph_svc }}
    -p WEB_TAG=stable
    | oc create -f -
  when: '"web" not in w_dc.stdout'

- name: Check Web Service
  shell: oc get svc
  register: w_svc
  changed_when: False

- name: Create Web Service
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-web-svc.yaml
    -p WEB_NAMESPACE={{ namespace }}
    | oc create -f -
  when: '"web" not in w_svc.stdout'

- name: Check Web Route
  shell: oc get routes
  register: w_r
  changed_when: False

- name: Create Web Route
  shell: >
    oc process -f {{ role_path }}/{{ t_dir }}/fs-web-route.yaml
    -p WEB_HOSTNAME={{ web_hostname }}
    | oc create -f -
  when: '"web" not in w_r.stdout'

# We don't wait for this pod,
# its deployment is controlled by Jenkins.
