---

# Simple 'hack' playbook to display secrets.
# Simply run this and supply the Ansible Vault key for the repo: -
#
#   $ ansible-playbook display-secrets.yaml --ask-vault-pass

- hosts: localhost
  tasks:
  - name: Display rsync secrets
    debug:
      msg: >-
        backup_rsync_user={{ backup_rsync_user }}
        backup_rsync_pass={{ backup_rsync_pass }}
        backup_rsync_host={{ backup_rsync_host }}
