---

# The Application's Persistent Volumes (Minishift).
#
# This expects these volumes in Minishift:
#
#   $(MINI_PATH)/pv-fs-cartridge-data
#   $(MINI_PATH)/pv-fs-pg-data
#
# oc process -f fs-pv-minishift.yaml | oc create -f -
# oc delete pv --selector template=fs-pv-minishift

kind: Template
apiVersion: v1
metadata:
  name: fs-pv-minishift
  annotations:
    description: Fragalysis Stack's Persistent Volumes (using Minishift)
    tags: fragalysis
labels:
  template: fs-pv-minishift

parameters:

- name: MINI_PATH
  value: /mnt/sda1/var/lib/minishift/openshift.local.volumes

- name: CARTRIDGE_NAMESPACE
  value: fragalysis-cicd
- name: CARTRIDGE_PV_SIZE
  value: 20Gi

- name: PG_NAMESPACE
  value: fragalysis-cicd
- name: PG_PV_SIZE
  value: 20Gi

objects:

# ---------------------------
# Database (Postgres) Volumes
# ---------------------------

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: fs-pg-data
  spec:
    capacity:
      storage: ${PG_PV_SIZE}
    accessModes:
    - ReadWriteMany
    hostPath:
      path: ${MINI_PATH}/pv-fs-pg-data/registry
    claimRef:
      name: fs-pg-data-claim
      namespace: ${PG_NAMESPACE}

# -------------------------
# Cartridge (RDKit) Volumes
# -------------------------

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: fs-cartridge-data
  spec:
    capacity:
      storage: ${CARTRIDGE_PV_SIZE}
    accessModes:
    - ReadWriteMany
    hostPath:
      path: ${MINI_PATH}/pv-fs-cartridge-data/registry
    claimRef:
      name: fs-cartridge-data-claim
      namespace: ${CARTRIDGE_NAMESPACE}
