---

- name: Create users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    groups: wheel
    home: "{{ os_volume_mount }}/{{ item.name }}"
  with_items: "{{ cloud_users }}"

- name: Add password-less sudo privilege
  copy:
    content: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/{{ item.name }}
  with_items: "{{ cloud_users }}"
