---

# Install packages slurm

- name: Install slurm packages
  yum:
    name:
    - epel-release
    - openssl
    - numactl
    - hwloc
    - lua
    - libibmad
    - libibumad
#  notify: Restart MUNGE

#- name: Add slurm (Galaxy) repository
#  yum_repository:
#    name: slurm
#    description: Galaxy slurm 18.08 packages
#    baseurl: https://depot.galaxyproject.org/yum/package/slurm/18.08/$releasever/$basearch/
#    gpgcheck: no
#    skip_if_unavailable: yes

#- name: Install slurm packages
#  yum:
#    name:
#    - slurm

- name: Crete slurm group
  group:
    gid: "{{ slurm_user_id }}"
    name: slurm
#  notify: Restart slurm

- name: Crete slurm user
  user:
    name: slurm
    uid: "{{ slurm_user_id }}"
    group: slurm
    home: "{{ slurm_home_path }}"
    create_home: no
    shell: /bin/bash
#  notify: Restart slurm

- name: Create slurm config directory
  file:
    path: /etc/slurm
    state: directory
    owner: slurm
    recurse: true
#  notify: Restart slurm

#- name: Copy slurm configuration template
#  template:
#    src: "{{ role_path }}/../head/files/slurm.conf.j2"
#    dest: /etc/slurm/slurm.conf
#    owner: slurm
#  notify: Restart slurm

- name: Copy slurm cgroup configuration
  copy:
    src: "{{ role_path }}/files/cgroup.conf"
    dest: /etc/slurm/cgroup.conf
    owner: slurm
#  notify: Restart slurm

- name: Copy slurm cgroup allowed devices configuration
  copy:
    src: "{{ role_path }}/files/cgroup_allowed_devices_file.conf"
    dest: /etc/slurm/cgroup_allowed_devices_file.conf
    owner: slurm
#  notify: Restart slurm

- name: Configure slurmd directory
  file:
    path: /var/spool/slurmd
    state: directory
    mode: 0755
    owner: slurm
    recurse: true
#  notify: Restart slurm

- name: Touch slurm log
  file:
    path: /var/log/slurmd.log
    owner: slurm
    state: touch
#  notify: Restart slurm
