---

# The Application's Persistent Volumes (NFS).
#
# This expects these volumes:
#
#   ${NFS_PATH}/pv-fs-cartridge-data
#   ${NFS_PATH}/pv-fs-neo4j-data
#   ${NFS_PATH}/pv-fs-neo4j-data-loader
#   ${NFS_PATH}/pv-fs-neo4j-log
#   ${NFS_PATH}/pv-fs-pg-data
#   ${NFS_PATH}/pv-fs-web-log
#   ${NFS_PATH}/pv-fs-web-media
#
# oc process -f fs-pv-nfs.yaml | oc create -f -
# oc delete pv --selector template=fs-pv-nfs

kind: Template
apiVersion: v1
metadata:
  name: fs-pv-nfs
  annotations:
    description: Fragalysis Stack's Persistent Volumes (using NFS)
    tags: fragalysis
labels:
  template: fs-pv-nfs

parameters:

- name: NFS_SERVER
  value: xchem-infra.novalocal
- name: NFS_PATH
  value: /exports

- name: CARTRIDGE_NAMESPACE
  value: fragalysis-stack
- name: CARTRIDGE_PV_SIZE
  value: 20Gi

- name: NEO4J_NAMESPACE
  value: fragalysis-stack
- name: NEO4J_DATA_LOADER_PV_SIZE
  value: 2Gi
- name: NEO4J_DATA_PV_SIZE
  value: 20Gi
- name: NEO4J_LOG_PV_SIZE
  value: 2Gi

- name: PG_NAMESPACE
  value: fragalysis-stack
- name: PG_PV_SIZE
  value: 20Gi

- name: WEB_NAMESPACE
  value: fragalysis-stack
- name: WEB_LOG_PV_SIZE
  value: 2Gi
- name: WEB_MEDIA_PV_SIZE
  value: 10Gi

objects:

# ---------------------
# Graph (Neo4J) Volumes
# ---------------------

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: fs-neo4j-data
  spec:
    capacity:
      storage: ${NEO4J_DATA_PV_SIZE}
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/pv-fs-neo4j-data
    claimRef:
      name: fs-neo4j-data-claim
      namespace: ${NEO4J_NAMESPACE}

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: fs-neo4j-data-loader
  spec:
    capacity:
      storage: ${NEO4J_DATA_LOADER_PV_SIZE}
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/pv-fs-neo4j-data-loader
    claimRef:
      name: fs-neo4j-data-loader-claim
      namespace: ${NEO4J_NAMESPACE}

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: fs-neo4j-log
  spec:
    capacity:
      storage: ${NEO4J_LOG_PV_SIZE}
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/pv-fs-neo4j-log
    claimRef:
      name: fs-neo4j-log-claim
      namespace: ${NEO4J_NAMESPACE}

# ---------------------------
# Database (Postgres) Volumes
# ---------------------------

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: fs-pg-data
  spec:
    capacity:
      storage: ${PG_PV_SIZE}
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/pv-fs-pg-data
    claimRef:
      name: fs-pg-data-claim
      namespace: ${PG_NAMESPACE}

# -------------------------
# Cartridge (RDKit) Volumes
# -------------------------

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: fs-cartridge-data
  spec:
    capacity:
      storage: ${CARTRIDGE_PV_SIZE}
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/pv-fs-cartridge-data
    claimRef:
      name: fs-cartridge-data-claim
      namespace: ${CARTRIDGE_NAMESPACE}

# -----------
# Web Volumes
# -----------

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: fs-web-log
  spec:
    capacity:
      storage: ${WEB_LOG_PV_SIZE}
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/pv-fs-web-log
    claimRef:
      name: fs-web-log-claim
      namespace: ${WEB_NAMESPACE}

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: fs-web-media
  spec:
    capacity:
      storage: ${WEB_MEDIA_PV_SIZE}
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/pv-fs-web-media
    claimRef:
      name: fs-web-media-claim
      namespace: ${WEB_NAMESPACE}
