---

# The Application's Persistent Volumes (NFS).
#
# This expects these volumes:
#
#   ${NFS_PATH}/pv-fs-cartridge-data
#   ${NFS_PATH}/pv-fs-pg-data
#   ${NFS_PATH}/pv-fs-jenkins
#   ${NFS_PATH}/pv-fs-input
#
# oc process -f fs-pv-nfs.yaml | oc create -f -
# oc delete pv --selector template=fs-pv-nfs

kind: Template
apiVersion: v1
metadata:
  name: fs-pv-nfs
  annotations:
    description: Fragalysis Stack's Persistent Volumes (using NFS)
    tags: fragalysis
labels:
  template: fs-pv-nfs

parameters:

- name: NFS_SERVER
  value: bastion.novalocal
- name: NFS_PATH
  value: /data

- name: CARTRIDGE_NAMESPACE
  value: fragalysis-cicd
- name: CARTRIDGE_PV_DIR
  value: pv-fs-rdkit-cartridge-data
- name: CARTRIDGE_PV_SIZE
  value: 20Gi

- name: PG_NAMESPACE
  value: fragalysis-cicd
- name: PG_PV_DIR
  value: pv-fs-postgresql-data
- name: PG_PV_SIZE
  value: 20Gi

- name: INPUT_NAMESPACE
  value: fragalysis-cicd
- name: INPUT_PV_DIR
  value: fs-input
- name: INPUT_PV_SIZE
  value: 50Gi

- name: JENKINS_NAMESPACE
  value: fragalysis-cicd
- name: JENKINS_PV_DIR
  value: pv-fs-jenkins
- name: JENKINS_PV_SIZE
  value: 10Gi

objects:

# ---------------------------
# Database (Postgres) Volumes
# ---------------------------

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: fs-pg-data
  spec:
    capacity:
      storage: ${PG_PV_SIZE}
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/${PG_PV_DIR}
    claimRef:
      name: fs-pg-data-claim
      namespace: ${PG_NAMESPACE}

# -------------------------
# Cartridge (RDKit) Volumes
# -------------------------

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: fs-cartridge-data
  spec:
    capacity:
      storage: ${CARTRIDGE_PV_SIZE}
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/${CARTRIDGE_PV_DIR}
    claimRef:
      name: fs-cartridge-data-claim
      namespace: ${CARTRIDGE_NAMESPACE}

# ---------------
# Jenkins Volumes
# ---------------

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: fs-jenkins
  spec:
    capacity:
      storage: ${JENKINS_PV_SIZE}
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/${JENKINS_PV_DIR}
    claimRef:
      name: jenkins
      namespace: ${JENKINS_NAMESPACE}

# -----------------------------
# Fragalysis Data-Input Volumes
# -----------------------------

- kind: PersistentVolume
  apiVersion: v1
  metadata:
    name: fs-input
  spec:
    capacity:
      storage: ${INPUT_PV_SIZE}
    accessModes:
    - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}/${INPUT_PV_DIR}
    claimRef:
      name: fs-input
      namespace: ${INPUT_NAMESPACE}
