---

# A developer-specific project deployment.
#
# This re-uses the production playbook with key variables set
# to create a new project that has its own database
# (without running backups) and uses the main graph database.
#
# Variables defined here replace any production role defaults.

- hosts: localhost
  gather_facts: No

  vars:
    namespace: fragalysis-rs
    namespace_display_name: "Fragalysis (Development-Rachael)"
    namespace_description: "The Fragalysis Project (Development-Rachael)"
    input_vol_name: fs-rs-input
    web_hostname: fragalysis-rs.apps.xchem.diamond.ac.uk

    backup_deploy: no

    wait_for_mysql: yes
    web_name: web
    web_image_tag: latest

  roles:
  - fragalysis-stack-prod
