---

os_auth_url: "{{ ansible_env.OS_AUTH_URL }}"
os_project_id: "{{ ansible_env.OS_PROJECT_ID }}"
os_username: "{{ ansible_env.OS_USERNAME }}"
os_password: "{{ ansible_env.OS_PASSWORD }}"
os_user_domain_name: "{{ ansible_env.OS_USER_DOMAIN_NAME }}"
os_region_name: "{{ ansible_env.OS_REGION_NAME }}"
os_key_name: stfc-abc-1
os_availability_zone: ceph

# A convenient authentication dictionary.
# Used by numerous OpenStack tasks.
os_auth:
  auth_url: "{{ os_auth_url }}"
  username: "{{ os_username }}"
  password: "{{ os_password }}"
  project_id: "{{ os_project_id }}"
  user_domain_name: "{{ os_user_domain_name }}"
