---

# Install packages for MUNGE, slurm and other stuff

- name: Install supporting packages
  yum:
    name:
    - epel-release
    - nfs-utils
    - nfs-utils-lib
    - munge
    - openssl
    - numactl
    - hwloc
    - lua
    - libibmad
    - libibumad

- name: Crete slurm group
  group:
    gid: "{{ os_slurm_user_id }}"
    name: slurm

- name: Crete slurm user
  user:
    name: slurm
    uid: "{{ os_slurm_user_id }}"
    group: slurm
    home: /var/lib/slurm
    shell: /bin/bash

- name: Create slurm config directory
  file:
    path: /etc/slurm
    state: directory
    owner: munge
    recurse: true
  notify: Restart slurm

#- name: Copy slurm configuration template
#  template:
#    src: "{{ role_path }}/files/slurm.conf.j2"
#    dest: /etc/slurm/slurm.conf
#    owner: slurm
#  notify: Restart slurm

- name: Copy slurm cgroup configuration
  copy:
    src: "{{ role_path }}/files/cgroup.conf"
    dest: /etc/slurm/cgroup.conf
    owner: slurm
  notify: Restart slurm

- name: Configure slurmd directory
  file:
    path: /var/spool/slurmd
    state: directory
    mode: 0755
    owner: slurm
    recurse: true
  notify: Restart slurm

- name: Initialise slurm logfile
  file:
    path: /var/log/slurmd.log
    state: touch
    owner: slurm
