---

# Our project/namespace...
namespace: fragalysis-stag

# Project-specific variables
mysql_name: mysql-stag
mysql_nfs_dir: pv-fs-s-mysql-data
mysql_vol_name: fs-s-mysql-data
use_nfs: yes
wait_for_mysql: yes
