#!groovy​

// The Fragalysis Stack (Django application) Database Builder.

pipeline {

  agent { label 'buildah-slave' }

  environment {
    USER = 'jenkins'
    REGISTRY = 'docker-registry.default:5000'
    STREAM_IMAGE = "${REGISTRY}/fragalysis-cicd/web-stream:latest"
    SOURCE_DATA_ROOT = '/fragalysis/django_data'
  }

  stages {

    stage('Inspect') {
      steps {
        dir('images/web') {
          script {
            DATA_ORIGIN = sh(script: './get_unbuilt_data_directory.py', returnStdout: true).trim()
          }
        }
      }
    }

    stage('Build') {
      when {
        expression { DATA_ORIGIN.length() > 0 }
      }
      steps {
        dir('images/web') {
          echo "Building ${DATA_ORIGIN}..."
          sh "cp /source-data/${DATA_ORIGIN}/* data-loader"
          sh "buildah bud --format docker --build-arg DATA_ORIGIN=$DATA_ORIGIN -f Dockerfile -t ${env.STREAM_IMAGE}"
        }
      }
    }

    stage('Push') {
      steps {
        script {
          TOKEN = sh(script: 'oc whoami -t', returnStdout: true).trim()
        }
        sh "podman login --tls-verify=false --username ${env.USER} --password ${TOKEN} ${env.REGISTRY}"
        sh "buildah push --tls-verify=false ${env.STREAM_IMAGE} docker://${env.STREAM_IMAGE}"
        sh "podman logout ${env.REGISTRY}"
      }
    }

  }

}
