---

# Create the cloud instances.
# This sets up some facts
# and dynamically adjusts inventory groups

- hosts: localhost
  roles:
  - cloud

# Configure the head and worker nodes

- hosts: head
  become: yes
  roles:
  - cloud-head

- hosts: worker
  become: yes
  roles:
  - cloud-worker

# Install common head and worker applications

- hosts: head:worker
  become: yes
  roles:
  - app-munge
  - app-slurm