---

- hosts: localhost
  roles:
  - cloud

- hosts: head
  become: yes
  roles:
  - cloud-head

- hosts: worker
  become: yes
  roles:
  - cloud-worker

- hosts: head:worker
  become: yes
  roles:
  - app-munge
  - app-slurm