---

# Create the cloud instances.
# This sets up some facts
# and dynamically adjusts inventory groups

- hosts: localhost
  roles:
  - cloud

# Configure the head and worker nodes

- hosts: head
  become: yes
  roles:
  - cloud-head
  tasks:
  - name: Build DRMAA
    include_role:
      name: slurm
      tasks_from: install-drmaa.yaml
  - name: Build slurm
    include_role:
      name: slurm
      tasks_from: build-slurm.yaml

- hosts: worker
  become: yes
  roles:
  - cloud-worker

# Install common head and worker applications

- hosts: head:worker
  become: yes
  roles:
  - app-munge
  - app-slurm