---

- hosts: localhost
  roles:
  - cloud

- hosts: slurm_head
  become: yes
  roles:
  - cloud-head
  - app-munge
  - app-slurm

- hosts: slurm_worker
  become: yes
  roles:
  - cloud-worker
  - app-munge
  - app-slurm