---

# Create the cloud instances.
# This sets up some facts
# and dynamically adjusts inventory groups

- hosts: localhost
  roles:
  - cloud

# Configure the head and worker nodes

- hosts: head
  become: yes
  roles:
  - cloud-head
  tasks:
  - name: Build slurm
    include_role:
      name: app-slurm
      tasks_from: build-slurm.yaml

- hosts: worker
  become: yes
  roles:
  - cloud-worker
  - app-munge
  - app-slurm
  tasks:
  - name: Start slurm daemon
    include_role:
      name: app-slurm
      tasks_from: start-slurm-d.yaml

# Install common head and worker applications

- hosts: head
  become: yes
  roles:
  - app-munge
  - app-slurm
  - app-slurm-drmaa
  tasks:
  - name: Start slurm controller daemon
    include_role:
      name: app-slurm
      tasks_from: bstart-slurm-ctld.yaml
