---

# Runs the main playbook in the cloud role.

- hosts: localhost
  roles:
  - cloud

- hosts: slurm_head
  become: yes
  roles:
  - head
  - munge

#- hosts: slurm_worker
#  become: yes
#  roles:
#  - munge

